### ISSUE TITLE
Crashes in Excel in Wine

### ISSUE THREAD

**Issue by ptwales** [retailcoder/Rubberduck#106]
_Low Priority_ and _likely impossible_ to fix.  But it would be nice.

Installer works without error in wine.  Excel 2010 crashes in wine upon opening the VBE.

    Unhandled Exception:
    System.Runtime.InteropServices.MarshalDirectiveException:
    > The type `System.Array' layout needs to be Sequential or Explicit
    at (wrapper native-to-managed) Extensibility.IDTExtensibility2:OnConnection   
    > (intptr,intptr,Extensibility.ext_ConnectMode,intptr,System.Array&)
    [ERROR] FATAL UNHANDLED EXCEPTION: 
    System.Runtime.InteropServices.MarshalDirectiveException: 
    > The type `System.Array' layout needs to be Sequential or Explicit
    at (wrapper native-to-managed) Extensibility.IDTExtensibility2:OnConnection 
    > (intptr,intptr,Extensibility.ext_ConnectMode,intptr,System.Array&)

_error message formatted with line-breaks._

**Comment by retailcoder** [comment]
not going to support this.
