### ISSUE TITLE
Find a way to merge CodeInspectionToolbar and CodeInspectionDockablePresenter functionalities

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#110]
Code is duplicated in the two places, and the dockable toolwindow can't "see" the toolbar, and the toolbar can't "see" the dockable toolwindow. Find a way to reuse the same code for the two UI's.

**Comment by ckuhn203** [comment]
Here's what probably needs to happen from a quick glance at the code.

1. Create a Base View class that has all the functionality the toolbar needs.
2. Create a Base presenter class with all of the functionality the toolbar needs.
3. The dockable presenter and dockable view inherit from these base classes, adding the functionality they need that is specific to the grid view.

**Comment by ckuhn203** [comment]
That won't work. We can't inherit from two separate classes. We'll be forced into implementing the interface and composing the dockable presenter.

**Comment by ckuhn203** [comment]
Some times you need to know when good enough is good enough, and I think that [extracting an `Inspector`][inspector] might have been enough. Both views communicate through that object now and although they both perform similar functions, they do it in very different ways. There is very little code reuse to be had here. Closing this issue.

[inspector]:https://github.com/retailcoder/Rubberduck/commit/1052b628e54fea17bc1d2d82ba1fceab93ecc656#diff-44e0e6380350c7dc6d4fa9143d4e950d
