### ISSUE TITLE
Stop Button on Test Explorer

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#141]
If Unit Tests or Code Under Test enters an infinite loop, there's no way to abort and stop the code. `Control + Break` doesn't work under this circumstance. A stop button on the test explorer would be a nice addition.

**Comment by retailcoder** [comment]
Ctrl+Alt+Break works for me. I don't think an `Application.Run` call can be aborted otherwise.

**Comment by retailcoder** [comment]
I don't see how this could be implemented. Closing issue.
