### ISSUE TITLE
Split Rubberduck into Two Projects

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#158]
The Public API is a mess. Move all UI elements that *have to be* com visible to a different project so all of this doesn't end up in the way of the user when they add a reference to Rubberduck for the unit testing functionality.

We should also properly wrap up any additional functionality we've added to the Extensibility LIbrary. We'll also expose the `SourceControlProvider`.

![ObjectExplorer](http://i.imgur.com/4duQgOD.png)

**Comment by retailcoder** [comment]
Suggesting `Rubberduck,API` assembly name.

Food for thought: say we want to make a `Rubberduck.API.Reflection` namespace, and expose everything currently under `Rubberduck.VBA.Nodes` in there, along with the `Rubberduck.VBA.VBParser` class.

`Rubberduck.API` should be referenced by `Rubberduck`, not the other way around. ...right?

**Comment by ckuhn203** [comment]
Are we talking about what it should look like to the person using the API or internally?

**Comment by retailcoder** [comment]
Both. Say there's a public API exposing the `SourceControlProvider` stuff - the `Rubberduck` project will need to reference the `Rubberduck.API` project in order to implement the GitHub integration. Or say there's a public API exposing the `VBParser` stuff - the `Rubberduck` project will need to reference the `Rubberduck.API` project in order to... well, parse the VBA code: `Rubberduck` will use the very same API it's going to be exposing to COM, right?

**Comment by ckuhn203** [comment]
In most cases, yes. It will be using the same API, but I would actually recommend moving the stuff we want to *hide*, not the stuff we want to expose. Client code should call `Rubberduck.AssertClass`, for example. While the UI elements should be tucked away somewhere no one's going to want to mess with them.

Extensibility may be an exception to this. Internally we'll use a lot of things that we *can't* expose to through COM becase it doesn't play well with overloads. That API will need to be very carefully crafted to not conflict too badly with Microsoft's extensibilty library. I haven't completely thought that through yet.

**Comment by ckuhn203** [comment]
No need to do this. I was able to clean up the API through a combination of making the assembly `[ComVisible(false)]` and hiding the items that have to be comvisible for the add-in to work, but we don't want as part of our public API.

Relevant commits.
 - e1fd4033566c9586fb17f2a6f6d04fff26749e5e
 - 3c090e8d153bd134bc806bc8b14af26c7044b484
 - 436246a713ac50fe6d3bf73881fa660590aeae43

Moving to Milestone Version 1.2 and closing issue.
