### ISSUE TITLE
Todo Explorer should sort from high priority to low

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#161]
Currently, it sorts from low to high.

![image](https://cloud.githubusercontent.com/assets/2716800/6062934/8fe8efec-ad21-11e4-8e9d-691f6575e68f.png)

**Comment by retailcoder** [comment]
I suggest default-sorting by `Project`, then `Module` *and then* by `Priority`. User should be able to simply click a column header to sort by priority regardless of project/module.

**Comment by ckuhn203** [comment]
I do like the click sorting. That thought crossed my mind too.

**Comment by ckuhn203** [comment]
This is an easy fix, but at some point in time someone changed the signature of `TodoItem`.
Because the datagridview is directly bound to a list of <TodoItem>s the UI is no longer displaying Project Name, Module Name, and Line Number. It instead displays a `Selection`... I'll need to dig through the commit history and see if I can't revert this change.

        private readonly TaskPriority _priority;
        public TaskPriority Priority{ get { return _priority; } }

        private readonly string _description;
        public string Description { get { return _description; } }

        private readonly QualifiedSelection _selection;
        public QualifiedSelection Selection { get { return _selection; } }

**Comment by ckuhn203** [comment]
This should be close to what is needed, but it might be better to set `AutoGenerateColumns` to false and explicitly build the data grid view. https://github.com/retailcoder/Rubberduck/blob/2a61444f95976fd59d6843a9c60d1a9775434d6c/RetailCoder.VBE/ToDoItems/ToDoItem.cs
