### ISSUE TITLE
Add a loading message to UI elements using the parser

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#171]
The parser isn't unusably slow, but it is slow enough that it makes some of the UI elements appear to be "frozen" for a few seconds. It would be a better UX to update the GUI with a "loading" message while the parser does its thing. It shouldn't be too hard to spin up a new thread to update the GUI until the parser is finished parsing.

Only these two seem to suffer from the issue.

 - [ ] TodoExplorer
 - [ ] CodeExplorer

**Comment by retailcoder** [comment]
Quick-fix alternative: make cursor a "wait" cursor.

**Comment by ckuhn203** [comment]
That could be good enough for v1.2, but I think I'd want to do something a little nicer long term.

**Comment by ckuhn203** [comment]
[Code Review here](http://codereview.stackexchange.com/questions/82160/displaying-a-wait-cursor-while-were-waiting).

The wait cursor seems more than sufficient for my small test project. Will decide if an actual "Loading..." message is necessary after running a real project through a pre-release build.

**Comment by ckuhn203** [comment]
9755a7b & 0fad6d0 make some improvements to the code explorer, but the cursor still doesn't show. I'm not 100% on how to fix the issue. Still needs some work.

**Comment by ckuhn203** [comment]
Better UI cues and performance now. Closing this issue (for now at least).
