### ISSUE TITLE
Define and Implement Public API for SourceControl & Git Integration

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#174]
IDE integration will be deferred to a future version, but I want to have a public API created and implemented for the `GitProvider` for version 1.2.

Below is the list of methods implemented in the stale [`source_control` branch](https://github.com/retailcoder/Rubberduck/tree/source_control). These items will need to be brought into the trunk and the remaining items implemented.

- [x] Clone
- [x] Init
- [x] Push
- [x] Fetch
- [x] Pull
- [x] Commit
- [x] Merge
- [x] Checkout
- [x] Undo
- [x] Revert
- [x] AddFile
- [x] RemoveFile
- [x] Status

**Comment by ckuhn203** [comment]
Example API I'd like to work with in VBA. 

    Option Explicit
    
    Sub CloneARepo()
        Dim git As New Rubberduck.GitProvider
        Dim repo As New Rubberduck.Repository
    
        With repo
            .Name = "NewProject"
            .LocalLocation = "C:\Path\to\new\repo\"
            .RemoteLocation = "https://github.com/ckuhn203/vbex/"
        End With
        
        Set git.Repository = repo
        
        git.Clone
        
        Dim wb As New Excel.Workbook
        wb.VBProject.Name = git.Repository.Name
        
        wb.SaveAs "C:\Path\to\new\workbook\location.xlsm"
    End Sub
    
    Sub WorkWithAnExitingHostedRepo()
        Dim wb As Excel.Workbook
        Dim xl As New Excel.Application
        
        xl.Visible = True
        
        Set wb = xl.Workbooks.Open("C:\Path\to\workbook.xlsm")
        Dim project As VBIDE.VBProject
        Set project = wb.VBProject
        
        Dim repo As New Rubberduck.Repository
        With repo
            .Name = project.Name
            .LocalLocation = "C:\Path\to\new\repo\"
            .RemoteLocation = "https://github.com/ckuhn203/vbex/"
        End With
    
        Dim component As VBIDE.VBComponent
        Set component = project.VBComponents.Add(vbext_ct_StdModule)
    
        component.Name = "NewStandardModule"
        component.CodeModule.AddFromString "Private helloWorld As String"
        
        Dim git As New Rubberduck.GitProvider
        With git
            .Repository = repo
            .project = project
            .UserName = "UserName"
            .Password = "Password"
        End With
        
        git.CreateBranch "newBranch"
        git.Commit "Added .bas file NewStandardModule"
        git.Push
        
        git.CheckOut "master"
        git.Pull
        git.Merge "newBranch"
        
        git.Revert 'Reverts the most recent commit. In this case, the Merge
    End Sub

**Comment by ckuhn203** [comment]
I like this API, but it introduces some difficulties. As currently defined, none of the classes have default constructors. COM exposure requires default constructors, and things normally passed into a constructor are set via properties. I think I'll introduce a layer of abstraction in between the classes we'll use internally and the ones that get exposed to COM Interop. Only trouble with that is naming becomes a problem. The naming issue may be able to be overcome by using `ProgId` attributes though.

**Comment by ckuhn203** [comment]
Relevant, but perhaps not the right way to go. http://stackoverflow.com/questions/28489915/how-to-create-a-read-only-property-exposed-to-com/28490784#28490784

This is much better advice.

> COM provides a class factory to create objects but it doesn't support passing arbitrary arguments. Which is why you always need a default constructor. Well, no problem, just create your own factory. Hide Class1 and write a Class1Factory class. With a CreateClass1() method that returns _Class1. It can take any arguments you need.

http://stackoverflow.com/questions/28489915/how-to-create-a-read-only-property-exposed-to-com?noredirect=1#comment45302564_28489915

Which would make client code look a little bit more like this.

    Dim factory As New Rubberduck.SourceControlProviderFactory
    Dim repo As Rubberduck.Repository
    Dim git As Rubberduck.GitProvider

    Set repo = factory.CreateRepository(project.Name, "C:\Path\to\new\repo\", "https://github.com/ckuhn203/vbex/")
    Set git = factory.CreateGitProvider(repo, project, username, password)  'or perhaps just take the required params directly and build the repo struct internally

    git.CreateBranch "newBranch"
    git.Commit "Added .bas file NewStandardModule"
    git.Push

**Comment by retailcoder** [comment]
^^ that. Much, much better! Keep the responsibility of *creating objects* on the COM-server side :)

**Comment by ckuhn203** [comment]
Yeah. The factory pattern is good. Here's the sample I'll work from when creating the COM visible API.

**Class**

    [Guid("B1E17DF6-9578-4D24-B578-9C70979E2F05")]
    public interface _Class1
    {

        [DispId(2)]
        string Message { get; }

        [DispId(1)]
        string TestingAMethod();
    }

    [Guid("197A7A57-E59F-41C9-82C8-A2F051ABA53C")]
    [ProgId("Rubberduck.SourceControl.Class1")]
    [ClassInterface(ClassInterfaceType.None)]
    public class Class1 : _Class1
    {
        public string Message { get; private set; }

        public Class1(string message)
        {
            this.Message = message;
        }

        public string TestingAMethod()
        {
            return "Hello World";
        }

**ClassFactory**

    [Guid("98F2287A-1DA3-4CC2-B808-19C0BE976C08")]
    public interface _ClassFactory
    {
        Class1 CreateClass1(string message);
    }

    [Guid("C7546E1F-E1DB-423B-894C-CB19607972F5")]
    [ProgId("Rubberduck.ClassFactory")]
    [ClassInterface(ClassInterfaceType.None)]
    public class ClassFactory : _ClassFactory
    {
        public Class1 CreateClass1(string message)
        {
            return new Class1(message);
        }
    }

**Comment by ckuhn203** [comment]
The discussion is over and everything mentioned here is implemented. Will track other changes/issues separately.
