### ISSUE TITLE
Remove [ComVisible(false)] attributes sprinkled everywhere

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#198]
The assembly itself is no longer COM-visible; these attributes can (should) be removed.

**Comment by ckuhn203** [comment]
This could be a really easy thing for someone wanting to get familiar with the code base to do.

**Comment by retailcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/5751684/6312763/9201f182-b953-11e4-825d-3cad601c4974.png)

**Comment by retailcoder** [comment]
143488a7 closes this issue.
