### ISSUE TITLE
Get Git Status

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#207]
Currently the `GitProvider` doesn't return a status. It would only throw an exception if it catches a `LibGit2Exception`, which is a failure state, but there can be other failure states. Need a way to pass Git Status results back to the client.

**Comment by ckuhn203** [comment]
This isn't quite what I meant to say. What I mean to say is it will be useful to report the results of  `Git Status` to the user so they can respond to situations appropriately.

**Comment by retailcoder** [comment]
:+1:

**Comment by ckuhn203** [comment]
Closed by commit c3f39743db5002ef839834503a0c7f8178942575
