### ISSUE TITLE
How should we handle version numbers?

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#212]
Up until this point, we have been using auto-build numbers on the assembly.
Should we continue to do this? On one hand, it's something we don't have to think about. VS just does it for us, but we lose some fine grain control over it and [semantic versioning](http://semver.org/) is not an option. Personally, I think this is okay so long as we start thinking a little bit more about the *file version*. I think we should start semantically version the file number. It's okay that it doesn't match the assembly. 

Thoughts @retailcoder?

On the flip side, I did find this article that recommends the exact opposite of what I'm proposing. 

> First of all, file versions and assembly versions need not coincide with each other. I recommend that file versions change with each build. But, don’t change assembly versions with each build just so that you can tell the difference between two versions of the same file; use the file version for that. Deciding when to change assembly versions takes some discussion of the types of builds to consider: shipping and non-shipping.

http://blogs.msdn.com/b/suzcook/archive/2003/05/29/57148.aspx

Perhaps a http://programmers.stackexchange.com/ question is in order.

**Comment by retailcoder** [comment]
The [AssemblyInfo.cs](https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Properties/AssemblyInfo.cs#L35-36) file contains this information.

>     [assembly: AssemblyVersion("1.1.*")]
>     [assembly: AssemblyFileVersion("1.1.0.0")]

The `AssemblyVersion` gives us the build number in the *About* window - and I like having the exact build number there. We could change the about window to display the `AssemblyFileVersion` so we still get the build number, and then use manual versioning on the `AssemblyVersion`, like this:

    [assembly: AssemblyVersion("1.1.0.0")]
    [assembly: AssemblyFileVersion("1.1.*")]

When we build the release build for 1.2, we change `1.1` for `1.2` in both assembly attributes, and leave the `*` alone - that way VS will keep incrementing the *file version* while the *assembly version* will remain at 1.2.0.0.. if that's what we want.

I just don't see a benefit in having different version numbers for *file version* and *assembly version* - this would be perfectly fine IMO:

    [assembly: AssemblyVersion("1.1.*")]
    [assembly: AssemblyFileVersion("1.1.*")]

The *Major* and *Minor* version numbers are manual ("semantic"?), and *Revision* and *Build* are provided automatically by Visual Studio / CSC.

I don't really mind having the "assembly version" say 1.1 for all 1.1 builds either... I just don't see a benefit to it.

**Comment by ckuhn203** [comment]
I was just confusing myself. We *have* to update the assembly every build in order for the add-in to work. My main concern was with client code (i.e. `AssertClass`) references breaking on each update. Short of moving the public API out of "core", there's nothing to change here. 

That's not something I want to do at this time. Closing issue.

**Comment by retailcoder** [comment]
`AssertClass` isn't likely to change very often. Deploying it separately isn't crazy at all.
