### ISSUE TITLE
Need to track currently active code pane before importing/exporting for SourceControl

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#213]
`SourceControlProviderBase` handles the import/export of code modules to the repository directory. Because all components are actually removed from the project, then re-imported during refresh actions, the IDE "jumps" to a different module. 

We'll need to keep track of the current code pane and set it back after any actions that remove a module.

**Comment by retailcoder** [comment]
That should be pretty easy, with `GetSeletion` and `SetSelection` extension methods.

**Comment by ckuhn203** [comment]
Easier said than done actually. I only had a moment to look at it, but getting a handle on a code pane (that temporarily disappears) isn't all that easy. Using a Qualified selection might work.
