### ISSUE TITLE
There should be a... static (?) IParserTree in RubberduckParser

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#215]
We are currently passing an `IRubberduckParser` in the construtor of anything that ever needs to parse VBA code - that's A Good Thing™, but we should be smarter than that: parsing all opened VBProjects is expensive (see #188), and there shouldn't be a need to parse once for showing the Code Explorer, *once more* to run code inspections from the Code Inspections window, *yet again* to run the same code inspections from the Code Inspections *toolbar*, ..and all of them run again when the window is closed/reopened... all while none of the VBA code was modified: this is highly inefficient and needs to be addressed.

We need to keep the last `IEnumerable<VBComponentParseResult>` results somewhere all copies of `IRubberduckParser` can access; I suggest a `private static` field that could be exposed with a public getter, something like:

    private static IEnumerable<VBComponentParseResult> _lastParseResults;
    public IEnumerable<VBComponentParseResult> LastParseResults { get { return _lastParseResults; } }

The only thing is that, well, there's not really a way of knowing if the VBE is "dirty"... or is there?

**Comment by ckuhn203** [comment]
There might be a way of knowing. [VBProject supposedly has a `IsDirty` property](https://msdn.microsoft.com/en-us/library/aa443818(v=vs.60).aspx).

**Comment by retailcoder** [comment]
I've seen `IsSaved`... but that only says if it was modified *since last save* - we need to know if it was modified *since last parse*.
