### ISSUE TITLE
Review inspection severity

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#237]
A lot of inspections show up as a "warning". While this may be appropriate for some inspections, we are under-using the "hint", "suggestion" and "error" severity levels.

Is it just because most of the implemented inspections are actually at "warning" level? I think we should classify them better for release 1.2 - let's discuss inspection severity levels here.

**Comment by ckuhn203** [comment]
Error is pretty severe as a default setting. It's the kind of thing that a team decides they don't want in their code base. Not exactly the kind of thing we can decide. I'm ok with under utilizing that one. 

Otherwise, yes. We need to create a list of all the implemented inspections for the docs anyway. So now is a good time to discuss what levels they should be at.

**Comment by retailcoder** [comment]
Indeed. Here's the inspections inventory, with their respective type and default severity level:

- `ImplicitByRefParameterInspection` (CodeQualityIssues) | Warning
- `ImplicitVariantReturnTypeInspection` (CodeQualityIssues) | Suggestion
- `MultipleDeclarationsInspection` (MaintainabilityAndReadabilityIssues) | Suggestion
- `NonReturningFunctionInspection` (CodeQualityIssues) | Warning
- `ObsoleteCallStatementInspection` (LanguageOpportunities) | Warning
- `ObsoleteCommentSyntaxInspection` (LanguageOpportunities) | Suggestion
- `ObsoleteLetStatementInspection` (LanguageOpportunities) | Warning
- `ObsoleteTypeHintInspection` (LanguageOpportunities) | Hint
- `OptionBaseInspection` (MaintainabilityAndReadabilityIssues) | Hint
- `OptionExplicitInspection` (CodeQualityIssues) | Warning
- `VariableNotAssignedInspection` (CodeQualiftyIssues) | Hint
- `VariableTypeNotDeclaredInspection` (CodeQualityIssues) | Warning

And then there are a few others down the pipeline:

- `CanPassByValInspection` (LanguageOpportunities) | Suggestion
- `ModuleOptionsFirstInspection` (MaintainabilityAndReadabilityIssues) | Suggestion
- `CanPromoteStaticLocalInspection` (MaintainabilityAndReadabilityIssues) | Hint
- `BadNameInspection` (MaintainabilityAndReadabilityIssues) | Suggestion
- `CanExtractGoSubProcedure` (MaintainabilityAndReadabilityIssues) | Warning
- `SetOnlyPropertyInspection` (MaintainabilityAndReadabilityIssues) | Warning
- `AssignedInDeclarationInspection` (LanguageOpportunities) | Hint
- `VariantUsageInspection` (MaintainabilityAndReadabilityIssues) | Hint
- `CanCollapseIfBlockInspection` (LanguageOpportunities) | Suggestion
- `CanReduceNestingInspection` (MaintainabilityAndReadabilityIssues) | Suggestion
- `UnusedFunctionReturnValueInspection` (CodeQualityIssues) | Suggestion
- `OnErrorResumeNextInspection` (CodeQualityIssues) | Warning
- `CanExtractRedundantCodeInspection` (CodeQualityIssues) | Suggestion

**Comment by ckuhn203** [comment]
* Obolete Call Statement : Suggestion  
* Obsolete Type Hint : Suggestion; Maintainability
* Variable Not Assigned : Warning (.Net won't let you even compile in this situation)
* Obsolete Let : Suggestion

* Implicit Variant Return Type & Variable Type Not Declared are basically the same issue. They should both be warnings. 

* Unused Function Return Val : Warning

Did I miss anything?

**Comment by retailcoder** [comment]
Closing this issue - open an [enhancement] issue if an inspection severity should be modified.
