### ISSUE TITLE
ReadMe file reads like a blog

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#238]
That readme file needs to get more to the point; let's keep the docs in the wiki, and let the readme be an entry point to the wiki pages - the time spent maintaining the readme file could be spent improving the wiki.

- [x] Move features section to wiki pages

The "coming up" section should also be in the wiki, on some *what's new in 1.2?* page.

- [x] Move coming up section to wiki pages

That leaves the intro (which could be revised), a list of links to wiki pages, and then all the bottom sections.

**Comment by ckuhn203** [comment]
The features should stay in the ReadMe. The read me is the first thing people see when they go to the repo. We shouldn't hide what the project does behind a link. I agree though, we could trim the readme down a bit.
