### ISSUE TITLE
VariableTypeNotDeclaredInspection gets confused with type hints

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#241]
This declaration yields a false positive:

    Dim foo$

Type of `foo` is `String`, `VariableTypeNotDeclaredInspection` should account for type hints.

**Comment by ckuhn203** [comment]
Could this rely on the TypeHint Inspection? If a node raises a warning for type hint, ignore  the type not declared? Not sure if that would be easier than "a real fix" or not. Just thinking out loud.
