### ISSUE TITLE
DLL Import calls confuse Paramater Can be Passed ByVal Inspection

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#250]
DLL import calls (WinAPI is the usual use case) cause the Code Inspection to somehow lose the Project & Component names.

	Private Declare Function RegOpenKeyEx Lib "advapi32" Alias "RegOpenKeyExA" _
	  (ByVal HKey As Long, ByVal lpSubKey As String, ByVal ulOptions As Long, _
	  ByVal samDesired As Long, phkResult As Long) As Long

	Private Declare Function RegSetValueExStr Lib "advapi32" Alias "RegSetValueExA" _
	  (ByVal HKey As Long, ByVal lpValueName As String, ByVal Reserved As Long, _
	   ByVal dwType As Long, ByVal szData As String, ByVal cbData As Long) As Long

Results in this:

![missing project & component names](https://cloud.githubusercontent.com/assets/2716800/6359781/6a0cf71a-bc43-11e4-839f-48898f0c179d.PNG)

Oddly enough though, the inspection would be correct ***IF*** it wasn't a function import. Being a function import, it's important that these remain `ByRef` because the call will return a value through the param. I'm thinking we could simply shut this inspection off if it finds the `Lib` token.

**Comment by retailcoder** [comment]
no need to search for a `Lib` token; the `ParameterListener` class is to blame here, more specifically this override:

        public override void EnterArg(VBParser.ArgContext context)
        {
            if (context.Parent.Parent.GetType() != typeof (VBParser.EventStmtContext))
            {
                _members.Add(new QualifiedContext<VBParser.AmbiguousIdentifierContext>(_memberName, context.AmbiguousIdentifier()));
            }
        }

`EventStmt` parser rule is explicitly ignored for the same reason. Ignoring `DeclareStmt` as well would fix this issue.

**Comment by ckuhn203** [comment]
:+1:
