### ISSUE TITLE
CI Suggests passing ParamArray ByRef

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#251]
CI suggests passing `ParamArray`s `ByRef`, but doing so causes a compiler error.

    Private Sub CreateShortcutMenu(ByVal NAME As String, ParamArray buttonIds() As Variant)

`ByVal` also causes a compiler error. So, basically, `ParamArray` is the same kind of token as those two and RD shouldn't recommend changing this. It's the *only* way to declare a `ParamArray` parameter.

**Comment by retailcoder** [comment]
Bring more like this. Bug:

                foreach (var procedure in procedures)
                {
                    var args = GetArguments(procedure);
                    foreach (var arg in args.Where(arg => arg.BYREF() == null && arg.BYVAL() == null))
                    {
                        var context = new QualifiedContext<VBParser.ArgContext>(module.QualifiedName, arg);
                        yield return new ImplicitByRefParameterInspectionResult(string.Format(Name, arg.AmbiguousIdentifier().GetText()), Severity, context);
                    }
                }

Fix:

                foreach (var procedure in procedures)
                {
                    var args = GetArguments(procedure);
                    foreach (var arg in args.Where(arg => arg.BYREF() == null && arg.BYVAL() == null && arg.PARAMARRAY() == null))
                    {
                        var context = new QualifiedContext<VBParser.ArgContext>(module.QualifiedName, arg);
                        yield return new ImplicitByRefParameterInspectionResult(string.Format(Name, arg.AmbiguousIdentifier().GetText()), Severity, context);
                    }
                }
