### ISSUE TITLE
Ignore Header Comments for Options First Inspection

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#253]
Not a priority and not *really* a bug, but it would be nice if the "Module Options Should be Specified First" Inspection would ignore comments before the options.

    ' requires Microsoft Visual Basic for Applications Extensibility 5.3 library
    
    ' Class: vbeCodeModule
    '   Interfaces with the vbeProcedures Collection to return both
    '   The VBIDE.CodeModule object and it's relevant vbeProcedures
    ' Author: Christopher J. McClellan
    ' Date Created: 5/30/14
    
    Option Compare Database
    Option Explicit

**Comment by ckuhn203** [comment]
Another good reason to change this. This is how we mark test modules.

    '@TestModule
    Option Explicit

Now I consider it to be a bug.

**Comment by retailcoder** [comment]
Disabled the inspection / closing this issue.
