### ISSUE TITLE
Fix links and Product Version 

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#256]
![image](https://cloud.githubusercontent.com/assets/2716800/6371345/ce681160-bcc8-11e4-9808-7da7efa517a2.png)

The Help Link should point to our Issues page?
The Support Link should definitely link to our repo. No idea why Installshield decided that our url was `Rubberduck.com`... Fix it.

Also, find a way to make sure the product version matches our assembly version.

Bonus round: Add a Rubberduck icon.

**Comment by retailcoder** [comment]
Bonus round 2: get a www.rubberduck-vba.com :)

**Comment by ckuhn203** [comment]
Fixed reference description and URL. Will open a separate issue for the icon.
