### ISSUE TITLE
"Variable is never used" is yielding false positives

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#260]
Consider a standard code module with the following public fields / globals:

    Option Explicit
    Public Strings As New StringType
    Public Fractions As New FractionType
    Public Data As New SqlCommand

Rubberduck considers them as never used, even though this line of code is found in the same project:

    Private Sub RaiseErrorMustImplementIComparable(member As String)
        Err.Raise 5, Strings.Format("{0}.{1}", ToString, member), "Invalid operation: method requires a list of numeric, date or string values, or a list of objects implementing the IComparable interface."
    End Sub

---

Usages (and assignments) are found *if they are in the same module* - this looks like `IdentifierUsageInspector` has a bug with usages of globals, but not with usages of fields.

**Comment by retailcoder** [comment]
Related: #282

**Comment by ptwales** [comment]
It also yields a false positive on `Assert` even when it is used in the same module.

    Option Explicit
    Option Private Module

    '@TestModule
    Private Assert As New Rubberduck.AssertClass

    '@TestMethod
    Public Sub ListCopyTest()
        Assert.AreEqual "List(1, 2, 3)", List.Copy(Array(1, 2, 3)).Show
        Assert.AreEqual "List()", List.Copy(Array()).Show
    End Sub

  Seems dissonant for Rubberduck to disapprove of it's own behavior.

**Comment by retailcoder** [comment]
Closing this issue, as the portrayed behavior has been corrected. However it seems an unused global somewhere, somehow makes an unused field be ignored.

**Comment by retailcoder** [comment]
This will need to be tested against the rebuilt grammar. Reopening, as variable usage detection code is pretty clumsy as of 1.21 - this is not over!
