### ISSUE TITLE
All grid views should be sortable

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#266]
#234 added sorting functionality to the Todo Explorer. All grid views should be sortable. Doing this right will require some refactoring so all our dockable windows can share [the code][commit].

        void SortColumn(object sender, DataGridViewCellMouseEventArgs e)
        {
            var columnName = Control.GridView.Columns[e.ColumnIndex].Name;
            IOrderedEnumerable<ToDoItem> resortedItems = null;

            if (columnName == Control.SortedByColumn && Control.SortedAscending)
            {
                resortedItems = Control.TodoItems.OrderByDescending(x => x.GetType().GetProperty(columnName).GetValue(x));
                Control.SortedAscending = false;
            }
            else
            {
                resortedItems = Control.TodoItems.OrderBy(x => x.GetType().GetProperty(columnName).GetValue(x));
                Control.SortedByColumn = columnName;
                Control.SortedAscending = true;
            }

            Control.TodoItems = resortedItems;
        }

[commit]:https://github.com/retailcoder/Rubberduck/blob/bd1a02dc42c7265028d68f55f95721672f89ec30/RetailCoder.VBE/UI/ToDoItems/ToDoExplorerDockablePresenter.cs#L39-L59

**Comment by retailcoder** [comment]
All grid views should also have a selection mode that selects the entire row. TODO explorer currently selects single cells.

**Comment by ckuhn203** [comment]
Duly noted.
