### ISSUE TITLE
Navigating to a deleted test module goes boom

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#279]
Steps to repro:

1. Add a new test module using the Test Explorer menu
2. Add a new test method using the Test Explorer menu
3. Remove the test module using the IDE's Project Explorer
4. Double-click the test method in the Test Explorer grid
5. Boom

A call to `Enumerable.First` blows up because the *sequence contains no element* - replacing `Enumerable.First` with `Enumerable.FirstOrDefault` and then handling the `null` case (i.e. removing the deleted test from the Test Explorer) would solve this issue.

**Comment by ckuhn203** [comment]
Two-fer. Commit a2715c5 closes this and #280.
