### ISSUE TITLE
"Variable is never assigned" is yielding false positives

### ISSUE THREAD

**Issue by PetLahev** [retailcoder/Rubberduck#282]
Hi Guys
I'm impressed by your progress. Just logging one minor one
This code
  
    Dim max As Double
    Dim pg  As MSForms.Page
          
    Set pg = MultiPage1.Pages("pgProgress")
    If prgVal > 0 And Not m_isPrgVisible Then
              
    MultiPage1.Style = fmTabStyleNone
    If m_LastPage Is Nothing Then Set m_LastPage = MultiPage1.SelectedItem  
    pg.Visible = True
    MultiPage1.Value = pg.Index

The **pg** variable is evaluated as never assigned. But you can see I use it quite extensively at the method
![variable is never assigned](https://cloud.githubusercontent.com/assets/11281023/6493774/366b0034-c2bd-11e4-8dd6-5d1afb3d6537.png)

**Comment by ckuhn203** [comment]
Thanks @PetLahev! We'll look into it and keep you updated.

**Comment by retailcoder** [comment]
Hmm no repro on my build:

![image](https://cloud.githubusercontent.com/assets/5751684/6546498/cd3de758-c58b-11e4-80bd-a87cd9feb66c.png)

**Comment by ckuhn203** [comment]
@retailcoder  have you tried this including the line numbers?

**Comment by retailcoder** [comment]
Line numbers are now known to break the parser, we need to modify the grammar to support them, and regenerate our lexer/parser - that will happen in the [GrammarIsFun] branch and I'd like release 1.3 to see an updated grammar.

So I'm blaming *this instance* on line numbers. But on a related note, `VariableNotUsedInspection` *is* yielding false positives: I've tested on a bigger/real project and I see no false positives for `VariableNotAssignedInspection`, but `VariableNotUsedInspection` doesn't seem to catch all usages of a variable.

Therefore, I'm closing this issue (keeping in mind that line numbers must eventually be supported by our grammar/lexer/parser), and focusing on #260.

**Comment by retailcoder** [comment]
Annoying; version 1.21 still yields false positives.
