### ISSUE TITLE
Fixing issue by the Code Inspections tool causes Compile error in a class that implements interface

### ISSUE THREAD

**Issue by PetLahev** [retailcoder/Rubberduck#283]
Version 1.2
Priority: Very Minor

Consider this code

    Option Explicit
    Implements IFilter

    Private m_Val   As Variant
    Private Property Let IFilter_CellValue(RHS As Variant)
    m_Val = RHS
    End Property

The **RHS** parameter will be marked in the inspection tool as
*Parameter RHS is passed as ByRef implicitly*
You click on the **Fix** button which will change the line to

    Private Property Let IFilter_CellValue(ByRef RHS As Variant)
and this cause a compilation error.

This is a class that implements an interface and in the interface I have this (implicit ByRef)

    Public Property Let CellValue(inVal As Variant)
    End Property
    Public Property Get CellValue() As Variant
    End Property
    Public Function Match(Criteria As ClsField) As Boolean
    End Function

You probably may have a check if a class implements an interface and disable or provide some message to user before fixing it

![fixing issue causes compilation error](https://cloud.githubusercontent.com/assets/11281023/6493948/a9026c62-c2be-11e4-8804-0237d40a589e.png)

**Comment by retailcoder** [comment]
Thanks for your precious feedback!

We'll look into it - interface implementations have been pretty much disregarded so far. Indeed, the tool shouldn't be recommending to change a method that's an interface implementation (or event handler / same thing really), but if the interface is in your project it would also suggest to change the interface's signature to pass `ByRef` explicitly... which would break all implementations.

Clearly we need some *change signature* refactoring to address this the right way!
