### ISSUE TITLE
TODO Explorer loaded empty even there are items to be displayed

### ISSUE THREAD

**Issue by PetLahev** [retailcoder/Rubberduck#285]
Version 1.2
Priority: Minor
OS: Win 7 64bit
Office: 2010 32 bit (at this particular case Excel)

I was playing a bit with the TODO screen (great stuff), all looks fine until I decided to remove **NOTE** from the form
1. Closed the TODO Explorer
2. Options - Removed Note from the options
3. Click Change
Got the message that the change will be reflected next time when the AddIn is loaded. 

Because I'm lazy 
1. I went to Add-Ins
2. Selected RubberDuck
3. unchecked the **Loaded/Unloaded** checkbox
4. then check it back (so the RubberDuck reloaded)
5. RubberDuck menu - TODO Items
6. The TODO Explorer appeared, there was an indication (the running circle) that something is loading but at the end the form stayed empty

You have to **manually** press the **Refresh**  button to get your changes. Reopening the form doesn't help. Once you manually refresh all is going to work without any issue

![todo explorer empty](https://cloud.githubusercontent.com/assets/11281023/6494897/6a25d216-c2c5-11e4-9f7d-f5ab6bcabecc.png)

**Comment by retailcoder** [comment]
Marking this one as a bug, since it was *supposed* to be fixed for 1.2 release...

**Comment by ckuhn203** [comment]
@retailcoder  Do we build the app `OnConnect` or `OnLoad`? I'm not sure if it's the issue (probably not), but we might have larger structural issues here. I'm trying to collect my thoughts on it.

**Comment by ckuhn203** [comment]
#269 was fixed in commit 0fdb219. This is somehow a subtly different issue.  I'll need to do some more research.

**Comment by ckuhn203** [comment]
#269 is not fixed. This **is** the same issue. It's just manifesting slightly differently.
