### ISSUE TITLE
Do we need a "development" branch?

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#288]
Yesterdays release, and the subsequent bug fixes I pushed to master have me wondering if we need a better branch/release strategy. We both know that, in theory, `master` should be the latest stable build, but often that isn't true. We're both guilty of treating `master` as a development branch as we work toward new releases. 

I was doing some [reading](http://nvie.com/posts/a-successful-git-branching-model/) and this seems like a good approach to me. The core idea is that, by definition, a commit to master is a release. All development happens in a `next` branch. When getting close to a release (think our last pre-release) we create a branch for it, and nothing but bug fixes go in after that. New features created after the `release` branch has been developed have to go into `next`. Production bug fixes get merged into both the `master` and `release` branch. 

There's a couple of benefits to this as far as I can tell. The biggest being we would never find ourselves in a situation where we have to wait for the next minor release to release bug fixes found in production. 

![Branch diagram][1]

  [1]:http://nvie.com/img/git-model@2x.png

**Comment by retailcoder** [comment]
Sure! The sooner the better!

**Comment by ckuhn203** [comment]
I created branch `next`. Next one to commit non-release changes to master flies a country over to buy the other a beer.

I'll add a section under Contributing about this then close the discussion.

**Comment by ckuhn203** [comment]
Updated read me. ccea70f1
