### ISSUE TITLE
Gracefully handle protected workbooks that can't be parsed

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#289]
Per [this comment](https://github.com/retailcoder/Rubberduck/issues/23#issuecomment-77345080).

> Hi guys,
> 
> I like what you've created here. I really want to use it, but this particular issue is something of a stumbling block for me. Where I work we have a couple of corporate XL add ins with protected code. Every time I open up one of Rubberduck menus (e.g the to dos). I get a pop up warning that it's found some code that it doesn't know how to analyse. Any idea when this particular issue might be fixed? It would be awesome if it can ignore the protected code a bit more quietly :-)
> 
> Cheers,
> Andy

We either need to detect the fact that a project is protected, gracefully (i.e. *silently*) handle the failure, or some combination of both.

**Comment by retailcoder** [comment]
Detecting that a project is locked is pretty simple:

        private void AddProjectNodes(VBProject project, TreeNode root)
        {
            var treeView = Control.SolutionTree;
            Control.Invoke((MethodInvoker)async delegate
            {
                root.Text = project.Name;
                if (project.Protection == vbext_ProjectProtection.vbext_pp_locked)
                {
                    root.ImageKey = "Locked";
                }
                else
                {
                    await AddModuleNodesAsync(project, treeView.Font, root);
                    root.Tag = new QualifiedSelection();
                    root.ImageKey = "ClosedFolder";
                }
            });
        }


![A locked project now appears with a padlock icon in the Code Explorer](http://i.stack.imgur.com/tfjQ7.png)
