### ISSUE TITLE
Package source code with the installer

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#290]
We're an open-source project. Let's package the source code along with the installer (perhaps as an option?)

**Comment by ckuhn203** [comment]
Since you want to learn to build the installer, I'll need to put the Setup Project in the repo. Before I do that, you'll need to [Enable Intallshield LE in Visual Studio](https://msdn.microsoft.com/en-us/library/dn531020.aspx).

> **To enable InstallShield Limited Edition**
> 1. On the menu bar, choose File, New, Project.
> 2. In the New Project dialog box, expand the Other Project Types node, and then choose the Setup and Deployment node.
> 3. In the template list, choose Enable InstallShield Limited Edition, and then choose the OK button.
> 4. In the browser window that opens, read the instructions, and then choose the Go to the download web site link.

**Comment by retailcoder** [comment]
:+1:

**Comment by retailcoder** [comment]
Looking at the release page, *source code is already available as a separate download*. Do we really need to package it with the installer?

**Comment by ckuhn203** [comment]
Personally, I would rather not make the download bigger than it needs to be, and I was always annoyed by those old Source Forge projects that distributed all of that source code along with the binaries.

**Comment by ckuhn203** [comment]
After reviewing the "open source" requirements that we're trying to hit, no. We don't have to include it.

> 2. Source Code
> The program must include source code, and must allow distribution in source code as well as compiled form. **Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code for no more than a reasonable reproduction cost preferably, downloading via the Internet without charge.** The source code must be the preferred form in which a programmer would modify the program. Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed.

http://opensource.org/docs/osd

Emphasis mine.

**Comment by retailcoder** [comment]
We're good then. Closing this issue.
