### ISSUE TITLE
Double-click on Code Explorer module-level node opens that module

### ISSUE THREAD

**Issue by mwolfe02** [retailcoder/Rubberduck#292]
In the Code Explorer window, in order to open a module one currently must expand the module's node and double-click on one of the procedure sub-nodes.

It would be nice if double-clicking on the module node would open that module directly, as it currently does in the built-in Project Explorer window.

**Comment by ckuhn203** [comment]
The double click navigation causes some problems. There's no good way to over-ride the default behavior of the tree view to expand/collapse the node on double click. What we really need is a different way for a user to trigger navigation.

How would everyone feel about a right-click navigation?
Or a right click context menu?
Perhaps a middle click action?

**Comment by retailcoder** [comment]
The toolbar could use additional buttons - a "Go" button similar to that on the *Test Explorer* toolbar would do.... and a context menu for the code explorer is already on the roadmap (see #231). I don't think a middle click action is good UX, not intuitive enough.

**Comment by ckuhn203** [comment]
A button requires re-directing the mouse pointer. I think it's a good UX to include one, but I think we should try to also find a way to navigate that allows the user to keep their pointer over the item they want to navigate to.

**Comment by retailcoder** [comment]
It's nonetheless awkward to have leaf nodes double-click/navigate, when non-leaf nodes don't react on double-click. The single most instinctive user action is a double-click. How about:

 - User double-clicks a tree node.
 - If that node has child nodes, remember whether it's expanded or collapsed.
 - Navigate to selected module.
 - Restore double-clicked node's expanded/collapsed state.

There might be a little twitch, but better that than awkward UX. Thoughts?

**Comment by mwolfe02** [comment]
Currently, if I double-click on a module node in the Code Explorer window, nothing happens.  That is, the node does not toggle between expanded and collapsed.  Should it?

I am running MS Access 2002/XP on a Windows 7 x64 machine.  Rubberduck is version 1.2 via the msi installer.

**Comment by ckuhn203** [comment]
No. That was disabled in order to fix an issue where double clicking the node both expanded/collapsed the node *and* navigated. It caused a very strange UX. Obviously, we need to do better.

**Comment by mwolfe02** [comment]
If it's possible, I would favor a design where expand/collapse was done via a single left-click on the +/- symbol or a {Space} keypress and navigation was done via a double-click of the node name or an {Enter} keypress.

This would allow for navigating the sample Code Explorer below using the following sequence of key-presses and mouse clicks (assume the entire node is collapsed to begin):

- {Left-Click} on Forms node: *select the Forms node*
- {Space} key press: *expand the Forms node*
- {W} key press: *jump to the first form that begins with 'W', WidgetDetail*
- {W} key press: *jump to the next form that begins with 'W', WidgetLookup*
- {Space} key press: *expand the WidgetLookup node (focus stays on WidgetLookup node)*
- {Enter} key press: *open the WidgetLookup module; place cursor at Ctl + Home position of WidgetLookup module*

```
- Forms
   + AddWidget
   + MainMenu
   + WidgetDetail
   - WidgetLookup
        Form_Open
        Form_Close
```

**Comment by ckuhn203** [comment]
I think that's ideal too. Originally, that's how it worked, but it had a bad side effect of  collapsing/expanding the node when you double clicked for navigation. This definitely deserves another look though. Maybe there is a solution I just haven't found yet.  

Spot on  with the key presses! Thanks for the idea! That's fantastic.

**Comment by retailcoder** [comment]
@mwolfe02 how about this?

![image](https://cloud.githubusercontent.com/assets/5751684/6544938/25635e92-c535-11e4-819a-2401e3b12ddd.png)

**Comment by mwolfe02** [comment]
@retailcoder That looks good.  I haven't had time to get the project set up locally to build from source, so I'll wait for the next release to check it out.  Thanks for incorporating my feedback!

**Comment by ckuhn203** [comment]
@mwolfe02 1.21 is done. We just need to build & package the installer. We will announce on http://www.rubberduck-vba.com/news.html once it's realeased. Thanks again for the great feedback.

**Comment by mwolfe02** [comment]
I just installed 1.21.  The Code Explorer looks great.  I'm going to try using it as a replacement for the Project Explorer and see how that goes.

**Comment by ckuhn203** [comment]
@mwolfe02 :+1:

**Comment by retailcoder** [comment]
The one missing functionality is "Delete" - I left it out because I want to implement a "Safe delete" instead (hopefully for 1.3), so that one can't just delete a module/class/form that's actually used somewhere.

Thanks again for the feedback!
