### ISSUE TITLE
Add @SessionStart and @SessionEnd annotations for test modules

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#293]
From rubberduck-vba.com's feedback form:

> **Subject**: Use setup/teardown methods in unit tests
> **Message**:
> Hello, I'm very interested by your framework !!! A first question: is it possible to define a method that must be executed before each TestMethod ? In JUnit framework, there are some tags : - `@Before` and `@After` : for methods to be executed before and after each test methods - `@BeforeClass` and `@AfterClass` : for methods to be executed before and after ALL test methods Bye Fred

---

`@TestInitialize` and `@TestCleanup` are already scheduled - let's take this opportunity to also add `@SessionStart` and `@SessionEnd` annotations for methods that must run once before/after all tests in a test module.

**Comment by retailcoder** [comment]
Actually, let's stick with MS-Test analogy, and use these annotations:

 - `@TestInitialize` to run a method before every test.
 - `@TestCleanup` to run a method after every test.
 - `@ModuleInitialize` and `@ClassInitialize` (depending whether module is std module or class), to run a method before tests start running.
 - `@ModuleCleanup` and `@ClassCleanup` (depending whether module is std module or class), to run a method after all tests have completed.

**Comment by ckuhn203** [comment]
Yes. You beat me to it. I like the MSTest analogy as well.

**Comment by retailcoder** [comment]
Unit tests in class modules are unfortunately not possible:  https://rubberduckvba.wordpress.com/2015/03/07/overcoming-limitations-testing-that-an-event-was-raised/

So only `TestInitialize`, `TestCleanup`, `ModuleInitialize` and `ModuleCleanup` have been implemented. See commit 5bcdb171e5a55b895f0a00266d84c23491a71768 for details.
