### ISSUE TITLE
Option Explicit is not specified on workbook or worksheet.

### ISSUE THREAD

**Issue by ptwales** [retailcoder/Rubberduck#295]
Code Inspector yields Option Explicit is not specified for workbook or worksheet module, which often never contain any code but may.

Perhaps if the module is blank ignore it?

**Comment by retailcoder** [comment]
But `Option Explicit` *is not specified*, right?

From the VBE options dialog, check the "Require Variable Declaration" box:

![image](https://cloud.githubusercontent.com/assets/5751684/6537107/af5e4036-c421-11e4-9ec8-630ab2086b36.png)

The VBE will automatically specify `Option Explicit` on workbook/worksheet modules; as a side-effect, Rubberduck will no longer warn about `Option Explicit` not being specified.
