### ISSUE TITLE
Suggestion: Don't say Suggestion without having an actual Suggestion.

### ISSUE THREAD

**Issue by Zomis** [retailcoder/Rubberduck#303]
> 1 issue found. Suggestion: Member 'CIV_draw' is implicitly Public - VBAProject.Module1, line 3

This isn't really a suggestion as it doesn't contain a suggestion for how to fix it, it is more of a warning / problem statement. Providing an actual suggestion, such as "Declare method public", is more helpful. (Perhaps even a quick-fix button or hotkey?)

**Comment by retailcoder** [comment]
Turns out there *is* a quick-fix implemented for that inspection :)

What you're seeing is only the result of pasting inspection results copied from the code inspections toolwindow.

Move along, nothing to see here...
