### ISSUE TITLE
Extract Method should insert the extracted method just below the calling one

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#304]
*Extract Method* refactoring currently inserts the new procedure *at the beginning of the code module*, which is slightly off-putting (i.e. downright annoying). The extracted method should be inserted immediately below the method it was extracted from.

**Comment by ckuhn203** [comment]
:+1:

**Comment by retailcoder** [comment]
Completed. ExtractMethodPresenter still needs to be refactored to use the `Declarations` API though.
