### ISSUE TITLE
No additional AddIn was found after installing Rubberduck 1.2.

### ISSUE THREAD

**Issue by knjname** [retailcoder/Rubberduck#305]
I installed Rubberduck 1.2 on Windows without old Rubberduck version.

And after installation of Rubberduck, I launched Excel and Excel VBE.
But there is no additional AddIn shown in AddInManager.
Any other tool bars and menu bars which come from Rubberduck are also couldn't be found.

Installation environment is:
 
* Windows 8.1 Pro x64 (Japanese edition)
* Office 2013 x64 (Japanese edition)
* .NET Framework 4.5.

Installation itself seems to be successfully done. I could find installed files as follows.

```
C:\Program Files (x86)\Rubberduck\Rubberduck
2015/02/09  07:07           198,656 Antlr4.Runtime.net45.dll
2015/02/10  19:43           762,880 git2-e0902fb.dll
2015/02/10  19:43           339,968 LibGit2Sharp.dll
2015/03/04  14:22           875,008 Rubberduck.dll
2015/03/04  14:22         1,889,792 Rubberduck.pdb
2015/03/04  14:22            11,652 Rubberduck.tlb
```

Similar defects are reported from Japanese users with the same version.

* http://clockahead.blogspot.jp/2015/03/vba.html (Windows8.1 + Office2013(64bit))
* https://twitter.com/thom__jp/status/575305439358799873 (office2013, win7 home.)

**Comment by retailcoder** [comment]
Hi @knjname and thank you for your support, that blogspot thread made my day! I'm sorry to hear Japanese users are having issues with getting Rubberduck to run, but unfortunately we don't have a Japanese environment to play with.

I would like to know, if you fork the repository and set up a development environment (Visual Studio 2013 Community Editition), does it work? If the issue is with the environment, then launching it in a debugger host with Visual Studio may yield valuable clues (/exceptions).

**Comment by ckuhn203** [comment]
I don't think this is related to the language. I think it is related to Office 2013 x64 bit. This software (nor the installer) have been tested in that environment. I think I recall reading somewhere that add-ins were slightly different for 2013 & 64 bit.

**Comment by danwagnerco** [comment]
I'm experiencing the same issue -- installer appears to have run successfully (same files as @knjname), but no Rubberduck option from the Add-in manager in VBE or the COM Add-ins manager from File > Options > Add-Ins > COM Add-ins.

My set up is:
* Windows 7 SP1
* Office 2013 x64
* .NET Framework 4.5.1

I'm downloading VS 2013 Community right now and will try to follow the build instructions to see if that offers y'all any more insight into the issue.

**Comment by ckuhn203** [comment]
Thanks @danwagnerco. Don't use the reg files in the root directory. The build instructions need to be updated. Here is the one key that should be needed. Visual Studio should handle the rest.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins\Rubberduck.Extension]
"LoadBehavior"=dword:00000003
"FriendlyName"="Rubberduck"
"Description"="Rubberduck add-in for VBA IDE."
"CommandLineSafe"=dword:00000000
```

**Comment by ckuhn203** [comment]
Found the article I was reading. Might have borked something when I built the installer. 

(or simply didn't target 64 bit.)

http://blogs.msdn.com/b/vsto/archive/2010/04/09/deploying-com-add-ins-for-64-bit-office-using-visual-studio-saaid-khan-for-nathan-halstead.aspx

**Comment by ckuhn203** [comment]
It's possible the extension needs to be registered in the `wow6432` node of the registry. If someone could try adding this key I'd be eternally grateful.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Wow6432Node\Microsoft\VBA\VBE\6.0\Addins\Rubberduck.Extension]
"LoadBehavior"=dword:00000003
"FriendlyName"="Rubberduck"
"Description"="Rubberduck add-in for VBA IDE."
"CommandLineSafe"=dword:00000000
```

It this solves the issue, I'll need to create a 64 bit version of the installer.

**Comment by retailcoder** [comment]
:+1:

**Comment by danwagnerco** [comment]
Hey @ckuhn203 / @retailcoder -- bad news. Either it's heavy user error or the registry key addition above is not the fix. Here are the steps I followed in my attempt:

1. Uninstall Rubberduck.
2. Create a `test_registry_key.reg` file on my desktop with the info above to make sure no dumb copy/paste errors happen.
3. Run `> regedit` from the command line.
4. File > Import then select the `test_registry_key.reg` file.

![image](https://cloud.githubusercontent.com/assets/6598675/6584927/95cf1780-c73c-11e4-8e31-b494d60a9cad.png)

I then ran the Rubberduck installer and restarted, but unfortunately Rubberduck still does not appear as an Add-in option.

**Comment by ckuhn203** [comment]
Dang. Thanks for trying @danwagnerco. I'm going to try building an installer targeted at 64x as soon as I have a moment. It could possibly be the Lib2git native binaries causing the issue on the 64 bit target. Or the current installer might be creating the required registry keys in the wrong place.

**Comment by retailcoder** [comment]
My bet is on the installer creating registry keys specifically for 32-bit Office.

All in!

**Comment by ckuhn203** [comment]
I think you're right @retailcoder. http://www.mztools.com/articles/2012/MZ2012013.aspx

**Comment by ckuhn203** [comment]
Wait... Maybe not. @danwagnerco can you try creating the extension reg key under `Addins64` instead of `AddIns` please?

**Comment by retailcoder** [comment]
[HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64\Rubberduck.Extension]
      "CommandLineSafe"=dword:00000000
      "Description"="Rubberduck add-in for VBA IDE."
      "LoadBehavior"=DWORD:00000003
      "FriendlyName"="Rubberduck"

**Comment by danwagnerco** [comment]
Hey @retailcoder -- I added that registry key but unfortunately now I can't open the VBE:

![image](https://cloud.githubusercontent.com/assets/6598675/6585880/38c0ecf6-c743-11e4-9518-2115c01505f7.png)

[cue the sad trombone from The Price Is Right...]

I'm going to delete that key for now.

**Comment by retailcoder** [comment]
Oh wow, that's a new one! I'll set up a 64-bit Office instance as soon as I can, we'll get a 64-bit Office build to work, one way or another. Thanks for your help!

**Comment by ckuhn203** [comment]
Yikes! Sorry @danwagnerco. Thanks for helping out. @retailcoder let me know when you're set up.

**Comment by retailcoder** [comment]
https://rubberduckvba.wordpress.com/2015/03/11/64-bit-rubberduck-a-work-around-until-release-1-21-soon/

**Comment by knjname** [comment]
@retailcoder 

Thanks, it's a great post. I tried it.

1. First of all, I couldn't find the registry entry ```HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64```,
but found ```HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins``` which had ```Rubberduck.Extension``` inside it.
2. I executed ```C:\WINDOWS\MICROSOFT.NET\FRAMEWORK64\V4.0.30319\REGASM.EXE /CODEBASE "C:\Program Files (x86)\Rubberduck\Rubberduck\Rubberduck.dll" /TLB```.
But there still wasn't Rubberduck addin.
3. I registered a new registry entry.
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64]

[HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64\Rubberduck.Extension]
"LoadBehavior"=dword:00000003
"FriendlyName"="Rubberduck"
"Description"="Rubberduck add-in for VBA IDE."
"CommandLineSafe"=dword:00000000
```
4. Finally I could found Rubberduck running on my Office x64!
![image](https://cloud.githubusercontent.com/assets/1453150/6600178/7a68e6ea-c851-11e4-8960-a299efdcb1e2.png)

**Comment by retailcoder** [comment]
:+1: Awesome! (and truly, what a relief!)

I hope you enjoy it as much as we do! We promise next release will be much easier to get to run on x64 - also note that quite a few bugs have been identified on 1.2 ..and most are fixed already, just not released yet; the most important one is that all module options (i.e. `Option Explicit` & others) must be specified **first** in a module (or not specified at all), see #286.

**Comment by ckuhn203** [comment]
Great! We'll be working on an actual x64 installer for the next release.

**Comment by danwagnerco** [comment]
Hey @retailcoder and @ckuhn203 -- really glad to hear that an x64 installer is in the queue. I unfortunately did not have as much success as @knjname, and after following his instructions wound up with a VISIBLE but not functional Rubberduck:

![image](https://cloud.githubusercontent.com/assets/6598675/6607954/0262807e-c811-11e4-84a8-233db4b6f858.png)

**Comment by retailcoder** [comment]
@danwagnerco That's a good sign - it means the `Addins64` key is ok, but then it's refusing to load because the assembly isn't properly registered.

Did you run `regasm.exe` on your installed dll? Open up an administrator command prompt and run this:

    C:\WINDOWS\MICROSOFT.NET\FRAMEWORK64\V4.0.30319\REGASM.EXE /CODEBASE "C:\Program Files (x86)\Rubberduck\Rubberduck\Rubberduck.dll" /TLB

If you get any weird output or error messages, please paste them here (the warning about Rubberduck not having a strong name key is normal).

**Comment by ckuhn203** [comment]
@danwagnerco  worst case, 1.21 shouldn't be more than a week or two away.

**Comment by retailcoder** [comment]
I can get Office 2010 x64 to run through the VS2013 debugger, but no luck getting it to work off an installer. The *minute* I get an installer to correctly register Rubberduck, 1.21 x64 gets released. @ckuhn203 as much as I'd like to release both x86 and x64 at the same time, I'm starting to think the x86 build should be released ASAP; we shouldn't penalize 32-bit Office users because we're (I'm) struggling with the x64 build...

**Comment by scottadoyle** [comment]
I just tried running the installer with runas admin.  I do not see it in the add-ins.  It installed into the Program Data folder.  My setup is: Window 10 64 bit OS.  Excel 2016 32 bit.

**Comment by Hosch250** [comment]
@scottadoyle Any particular reason you aren't using 1.4.3?  This release brings a bunch of new improvements and bug fixes (and a few new bugs too, many of which are fixed for the next release, but we are in the middle of several very major changes, so that may be a while).

**Comment by scottadoyle** [comment]
I had recently installed rubberduck.  I have not used it much.  Programming
is not my primary job responsibilities.  I thought I had downloaded and
installed the newest version.

I am looking forward to learning how to use the github integration.

**Comment by ckuhn203** [comment]
@scottadoyle please be aware that the Git integration isn't fantastic or stable yet (10/8/15). I hope to get it working correctly over the winter.
