### ISSUE TITLE
Create Build Configurations for x86 and x64

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#306]
Related to #305 and commit 9427f125

We need build configurations that specifically target different versions of Office. It's possible to [conditionally execute Post-Build events based on the Configuration's Name][so], so it's possible to do this. 

>     if $(ConfigurationName) == Debug xcopy something somewhere

We'll need the following build configs.

- Debug86x 
- Debug64x
  * Use 64 bit regasm instead of Visual Studio to register assemblies.
  * `c:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe /codebase $(TargetPath) /tlb`
- DebugAccess86x 
  * this one is so ducky can launch Access instead of Excel just by hitting the "Start Debug" button
- Release86x
  * Copy the 32 bit native binary of libgit2 to the root folder of the bin
- Release64x
  * Copy the 64 bit native binary of libgit2 to the root folder of the bin

We will also need a second set up project to build a 64x installer, or possibly an easy way to flip the installer from 64x to 86x. 

[so]:http://stackoverflow.com/q/150053/3198973

**Comment by retailcoder** [comment]
post-build events are only for debugging; coming up with a post-build script that works for both 32 and 64 bit targets will only be a convenience for ourselves.

The 32-bit installer needs to run x86 regasm and the 64-bit installer needs to run x64 regasm to register the assembly.

Note that regasm is warning about the assembly not having a strong name, because of the `/codebase` switch (which is required). Currently we can't have a strong name key because LibGit2Sharp doesn't have one...

**Comment by ckuhn203** [comment]
Post build events **aren't** only for debugging. The post build copies the proper libgit2 binary into the root folder of the bin so the installer can find it. Also, I am strongly opposed to having the installer run regasm. The installer running regasm will mean it can not remove the registry keys it creates unless we specifically build an un-install program. That's not something I really want to do.

**Comment by retailcoder** [comment]
Ran x64 installer with debug-x64 config, seems to work (hard to tell, ran on dev environment - but Wix setup didn't get to that point yesterday), but assembly is still self-registered. I wonder...

**Comment by ckuhn203** [comment]
The way I set up the post-build, it only copies the libgit2 binary to the correct place if it's built with the `Release64` config. I can change it if you like. Also, I can go ahead and create the Setup64 project if you like. I can copy most of it over from our current setup project.
