### ISSUE TITLE
Thank Duga ...and review About window

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#308]
We need to re-look at the About window. Simon/Skiwi's Duga chat bot has been useful beyond words so far, it deserves a little "thank you".

**Comment by ckuhn203** [comment]
:+1: Yes yes. They deserve much more than a thank you, but it's the least we can do.

**Comment by retailcoder** [comment]
The 1.21 about window will look something like this:

![about window](https://cloud.githubusercontent.com/assets/5751684/6650436/214e4ab2-c9e8-11e4-947c-299d2e552dce.png)
