### ISSUE TITLE
Allow installation without Local Admin privileges

### ISSUE THREAD

**Issue by christophocles** [retailcoder/Rubberduck#310]
The installer should allow installation of the addin without requiring local administrator privileges.  The installation can be performed with a limited local user account on a per-user basis, by registering the classes in the HKEY_CURRENT_USER registry branch.

**Comment by retailcoder** [comment]
We are currently working in the installers for 1.21 - we'll try to make it
happen! @ckuhn203 any showstopper on this one?

**Comment by ckuhn203** [comment]
If it's as easy as it *should* be, we can do this for 1.21. If It turns out to be more difficult than I thought, will kick it down to 1.3. Either way, @christophocles  is correct. There's no reason we shouldn't have a per user install. VBE add-ins are per user to begin with.

**Comment by christophocles** [comment]
For other, similar addins, I have created a modified .reg file to perform a manual non-admin installation.  This was done by exporting all relevant registry keys from HKLM, and then replacing HKLM with HKCU.  I am thinking the Installer should also be capable of doing this.

**Comment by ckuhn203** [comment]
Yes, the installer is absolutely capable of it. I think I'm more concerned about the registration of the API than anything.

**Comment by christophocles** [comment]
I just tried to do a user install with v1.21 and I don't think it's possible.  The default install folder is "C:\Program Files (x86)\Rubberduck\Rubberduck" and obviously this folder requires admin.  I manually changed the folder to a local user folder, but the installer still requires elevation to continue.  Note the Elevation symbol on the "next" button in the screenshot.

![image](https://cloud.githubusercontent.com/assets/5281163/6679248/3855517e-cc13-11e4-9971-208d74fafaa2.png)

The installer may not be checking if Elevation is required, and is requesting it regardless.  Or it may intend to register the classes in HKLM\Classes, which will always require Elevation. 

For the per-user install to work, two things need to happen: the addin .dll file is installed to a local user folder (i.e. %APPDATA%\Roaming), and the Classes are registered in HKCU\Classes.  Ideally, the installer should first let the user select a Per-User or System-Wide install, and then the set the default install folder and class registry keys to appropriate locations.

**Comment by ckuhn203** [comment]
Okay. I wasn't 100% sure that had worked. I followed the [instructions from installshield](http://helpnet.installshield.com/isxhelp20/Content/helplibrary/IHelpRunTimePerUserSetups.htm), but I must have missed something. I'll see if I can't make this happen for 1.3 instead. The bug fixes were a priority. I honestly don't understand why the classes weren't registered under HKCU. Will take a look at my test machine in the morning to see where the CLSIDs were registered.

**Comment by retailcoder** [comment]
Classes are registered under HKCR/CLSID. I'm still working on geting a x64 installer to work, I'll try registering them under HKCU/Software/Classes/CLSID and see what I get - that's pretty much the one thing I haven't tried as of yet.. hold on......

**Comment by ckuhn203** [comment]
I'm also going to call out that all installs are "per user" regardless of the installer settings, required rights, or location of the CLSIDs in the reg. the add-in can only be registered for the current user. I understand that doesn't change anything here. Just something to keep in mind.

**Comment by ckuhn203** [comment]
> If an installation is running in maintenance mode, the InstallScript engine determines the value of the ALLUSERS variable based on whether the initial installation was installed as per-user or per-machine (based on the location of where the uninstallation information was installed).

http://helpnet.installshield.com/installshield18helplib/mergedProjects/installshield18langref/ALLUSERS.htm

Please try a clean install instead of an upgrade. (Make sure to back up your  `rubberduck.config` file first.)

**Comment by christophocles** [comment]
I uninstalled the addin first.  The screenshot above is from a clean install.

**Comment by ckuhn203** [comment]
I'll look farther into it, but an admin-less install may not be possible with all the COM registration that happens. Please feel free to fork and attempt a fix if we don't get to it in a timely manner.

**Comment by christophocles** [comment]
@retailcoder just fyi... HKCR is not the true location where classes are registered.  It mirrors the contents of other locations:

The content of HKEY_CLASSES_ROOT comes from two sources: HKEY_LOCAL_MACHINE\SOFTWARE\Classes and HKEY_CURRENT_USER\SOFTWARE\Classes. If a subkey or entry appears in either location, then it also appears in HKEY_CLASSES_ROOT. If the values of entries in the two Classes subkeys conflict, then only the value in HKEY_CURRENT_USER\SOFTWARE\Classes appears in HKEY_CLASSES_ROOT.

https://technet.microsoft.com/en-us/library/cc739822%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396

**Comment by retailcoder** [comment]
@christophocles same for HKCR/wow6432node I'm guessing?

**Comment by christophocles** [comment]
@retailcoder I believe so, yes.

@ckuhn203 I appreciate you guys spending the time on this, I know it is not a high priority versus other tasks.

When I have time this week, I do plan to hack together a registry key to install this addin on my work PC, same as what I did for MZ-Tools v3.  After I have it running I will show you what I did.

**Comment by ckuhn203** [comment]
Thanks @christophocles. I imagine it involves exporting the keys and creating a .reg file manually? I may be able to assist in that endeavor tomorrow if I have a few extra minutes.

**Comment by ckuhn203** [comment]
I might have found what I missed. Will follow up. http://helpnet.installshield.com/installshield16helplib/SpecifyingRequiredExecution.htm

**Comment by retailcoder** [comment]
I've just experimented a bit - it seems the only keys that matter are under HKLM (excluding the add-in key itself, registered under HKCU/Software/Microsoft/VBA/VBE/6.0/Addins64). I successively removed them from everywhere I saw them and launched Excel only to see Rubberduck still alive - it only died when the HKLM keys were removed. I'm giving up on this one.

**Comment by christophocles** [comment]
I can confirm that in v1.21, all of the CLSIDs are registered in HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID.  This was not the case in v1.2.

The only registry keys in HKLM are the ones related to the installer/uninstaller.

**Comment by retailcoder** [comment]
Ok I think I scrubbed my whole registry clean - backing up, I'll give it another shot.

The Wow6432Node keys are only for 32-bit software running on x64 right? You seem to know your registry stuff, do you think this would be a working setup for a x64 build?

![image](https://cloud.githubusercontent.com/assets/5751684/6680629/6ebf5666-cc30-11e4-8fa6-12eac1910f28.png)

**Comment by christophocles** [comment]
@retailcoder correct. Wow6432node is used for 32-bit applications on x64 OS.  So the 32-bit addin has its CLSIDs under Wow6432node, but the 64-bit addin would not.

The part that actually makes the VB editor load the addin is this key (for 32-bit): HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins\Rubberduck.Extension

For 64-bit, it appears to be:
HKEY_CURRENT_USER\Software\Microsoft\VBA\VBE\6.0\Addins64\Rubberduck.Extension

So yes, I think your setup looks correct.  But I don't have a copy of 64-bit office to test it.

This seems to confirm what I just said:
http://www.mztools.com/articles/2012/MZ2012018.aspx
