### ISSUE TITLE
Localize!

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#318]
Rubberduck is currently {en-US}, often with hard-coded strings.

Let's prepare Rubberduck for localization, and MOVE ALL THE STRINGS to resource files.

Then we can translate these strings and have Rubberduck be displayed in the same language as our users' IDE.

**Comment by ckuhn203** [comment]
1.3 might be a bit ambitious. I don't think the free version of install shield we're using can handle this. So, this will not only require a significant re-factoring, but we'll also need to move to a WiX installer. I'm not ruling it out for that version or arguing against it. Just hedging my bets on the timeline.

**Comment by retailcoder** [comment]
https://i.imgflip.com/iwsr8.jpg

**Comment by retailcoder** [comment]
The installer can remain {en-US} if it can't be localized.. that shouldn't stop us from localizing Rubberduck itself :)

**Comment by retailcoder** [comment]
1.3 is too early for this. Let's try for 1.4.

**Comment by retailcoder** [comment]
Still a number of issues, notably in the settings dialog and gridviews - not closing just yet.

**Comment by retailcoder** [comment]
still a number of issues, but they can be addressed on new GitHub issues. Closing this one.
