### ISSUE TITLE
'Rubberduck' v1.21 could not be loaded for Excel 2013

### ISSUE THREAD

**Issue by danwagnerco** [retailcoder/Rubberduck#320]
Hey team -- argh, another Office 2013 x64 issue!

After a fresh install (via Rubberduck.v1.21.Setup.x64.exe) following all the defaults (`%HOMEPATH%\AppData\Roaming\Rubberduck.Install` install path), I get an error message indicating that the Rubberduck add-in could not be loaded after opening the VBE from Excel:

![image](https://cloud.githubusercontent.com/assets/6598675/6692168/1375e3ec-cc99-11e4-9c73-310b6aaa5948.png)

If it would be helpful, I can provide the installer log file.

I'm using Windows 7 SP1 and Excel 2013 64-bit.

**Comment by ckuhn203** [comment]
It might be @danwagnerco. It could at least help us figure out if it's an issue with 2013 or x64. Both are a bit suspect at the moment, but the x64 installer was tested on 2010 I believe.

**Comment by retailcoder** [comment]
x64 installer confirmed to work on 64-bit Office 2010.

Did you uninstall the previous 1.2 version?

Try running `c:\windows\microsoft.net\framework64\v4.0.30319\regasm.exe (install-folder)\rubberduck.dll /codebase /tlb` - just to be sure ;)

**Comment by danwagnerco** [comment]
I did @retailcoder (fearing the worst lol) but let me run that from CMD and try it again. Stby...

**Comment by danwagnerco** [comment]
After running an uninstall from 'Add or Remove Programs', this is the correct result from regasm.exe, right?

![image](https://cloud.githubusercontent.com/assets/6598675/6692534/212bacf4-cc9b-11e4-8b4c-b2be26e8a06d.png)

I tried the installer again but got the same bummer error message... :cry:

**Comment by retailcoder** [comment]
wait, is the dll even *there*?

**Comment by danwagnerco** [comment]
After removal, nope -- but when I run the installer it looks right. Here's the CMD results after running the installer:

![image](https://cloud.githubusercontent.com/assets/6598675/6692771/c06cc4be-cc9c-11e4-806b-9f8b87ec0433.png)

**Comment by retailcoder** [comment]
that should be it. how isn't regasm.exe finding the assembly?!

**Comment by retailcoder** [comment]
the cmd window is running with admin privileges right?

**Comment by ckuhn203** [comment]
Sounds dumb, but have you tried not using the `%HOMEPATH%` environment variable? 

*Grasping at straws* :cry:

**Comment by danwagnerco** [comment]
Argh here's what I just tried:

![image](https://cloud.githubusercontent.com/assets/6598675/6692867/5e434258-cc9d-11e4-8192-13fc6d9ec74b.png)

This is me trying as admin:

![image](https://cloud.githubusercontent.com/assets/6598675/6692903/903974ee-cc9d-11e4-9071-df523b0bb515.png)

Progress!

**Comment by retailcoder** [comment]
the warning is normal. launch excel now, I'm expecting it to work! :)

**Comment by danwagnerco** [comment]
F YAAAAAAA!

![jackpotttttttttt](https://cloud.githubusercontent.com/assets/6598675/6692990/23f68424-cc9e-11e4-91d8-4151b8d36895.png)

**Comment by retailcoder** [comment]
(where's the "like" button?) :+1:

**Comment by retailcoder** [comment]
looks like there's still a bit of work/testing to do with the registration of the x64 install.

**Comment by ckuhn203** [comment]
@retailcoder perhaps there's an issue with the *.tlb file provided with the installer? Or the keys perhaps?

**Comment by retailcoder** [comment]
Has to be the keys... the tlb is only for the unit testing. But then I got the keys from regasm /regfile off the very last build... could I have accidentally rebuilt the dll when building the installer? Hmmm....
