### ISSUE TITLE
Exclamation points in MS Access VBA not handled correctly by parser

### ISSUE THREAD

**Issue by mwolfe02** [retailcoder/Rubberduck#321]
Consider the following standard code module:

    Option Explicit
    
    Private Sub Test1()
        Debug.Print Forms("MainMenu").Name
    End Sub
    
    Private Sub Test2()
        Debug.Print Forms!MainMenu.Name
    End Sub
    
    Private Sub Test3()
    
    End Sub

This module will be displayed in Code Explorer as such:

    - Module1
        Test1
        Test2

Note that Test3 is not shown in Code Explorer.  Double-clicking on Test2 in Code Explorer highlights the following text only:

    Private Sub Test2()
        D

**Comment by retailcoder** [comment]
Definitely a grammar issue. Thanks!

**Comment by retailcoder** [comment]
will need further testing, but looks fixed
