### ISSUE TITLE
Code Explorer needs a rename option

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#322]
When right clicking on an item in the Code Explorer, it would be great to have a "Rename" option. Not only does this move us toward removing the need to ever open the built in Project Explorer, but it also would mean there's almost never a need to open up the Properties view.

**Comment by retailcoder** [comment]
Related: #185, #284

**Comment by retailcoder** [comment]
Renaming a module, class, or procedure/function, needs to have cascading effects on the entire code base - these effects are globally referred to as a "rename refactoring".

**Comment by christophocles** [comment]
Yes this is a highly desirable feature for me.  #1 on my list :)   I have hundreds of one- or two-letter procedure names and variable names that need to be (safely) renamed to something meaningful.

**Comment by retailcoder** [comment]
@christophocles it's number 1 on my list as well! ;)

**Comment by retailcoder** [comment]
@christophocles  you'll be happy to hear that the *rename* refactoring is now in the [Next] branch - that one's going to be a :bomb:!!
