### ISSUE TITLE
Create replacement for Locals window

### ISSUE THREAD

**Issue by mwolfe02** [retailcoder/Rubberduck#325]
The VBA Locals window appears to have a bug that prevents it from displaying property values of classes that implement an interface: [StackOverflow: How to get property values of classes that implement an interface in the Locals window?](http://stackoverflow.com/q/29146243/154439)

Unless a workaround is found for that issue it seems like the only option will be to replace it entirely.

**Comment by retailcoder** [comment]
The black magic wizards behind [vbWatchDog](http://www.everythingaccess.com/vbwatchdog.asp) would *maybe* be able to do this. I'm not.

**Comment by mwolfe02** [comment]
I'll contact Wayne at vbWatchDog and see if he has any interest.

**Comment by retailcoder** [comment]
@mwolfe02 what?! Awesome! And while you're at it, it would be beyond awesome if we could have a lead on how they managed to add that sidebar to the codepane window - I'd like to have that and show icons there, on the lines with code issues.. and if possible to make that icon clickable so we could have a little drop-down showing the quick-fix options... okay I'm pushing it. But a hint on the call stack magic would be wonderful :)

**Comment by mwolfe02** [comment]
I just sent him a message on LinkedIn.  I'm not sure how willing he'll be to part with the call stack secret sauce, but I told him he should check out the project either way.  I'll let you know if I hear back from him.

**Comment by retailcoder** [comment]
I'm not expecting anything about the call stack sauce to be spilled into the Open-Source world - after all, it's their highlight and they're *selling* their product. But thanks a lot for this @mwolfe02, it's unexpected and welcome help :)

**Comment by mwolfe02** [comment]
I just got a response from Wayne Phillips with vbWatchdog.  As one would expect, he's not real eager to give away the call stack code.  I was a bit surprised/enlightened to learn that in addition to C++, implementing vbWatchdog involved actual assembly-level programming:

>Hi Mike, 
>
>Thanks for your message. I will check it out when I get chance. 
>
>You're right, it's a tricky one. The callstack features of vbWatchdog are at the core/heart of the product, and so that information is very commercially sensitive given that it's a very unique feature. 
>
>If it were for a commercial product, then a licencing arrangement could be discussed, but for a free open source product that's just not going to be feasible. 
>
>Accessing the VBA callstack requires hardcore assembly and C++ programming, as well as significant knowledge of the VBA innards to make it all work. This challenge is certainly not something for the faint hearted, and I wish them luck... 
>
>Cheers 
>
>Wayne

**Comment by retailcoder** [comment]
Bwahahahaha this is sooooo not happening!

**Comment by retailcoder** [comment]
Thanks @mwolfe02!

**Comment by mwolfe02** [comment]
Yeah, I feel even better about paying for my vbWatchdog license after reading his response.  And, don't tell him I said this, but I think he's waaaaaay undercharging for his product.

**Comment by retailcoder** [comment]
Still, it's awesome that 1) you know someone there, 2) that someone answered, and 3) he'll take a look at our project!

**Comment by ckuhn203** [comment]
I figured as much. Thanks for trying @mwolfe02.

**Comment by sancarn** [comment]
Hi all,

I realise this was closed a looong time ago, but I've been doing some [research](https://github.com/sancarn/VBA-STD-Library/blob/master/docs/STD_Types_String.md) that you might be interested in! :)

I'm mainly researching this because I want to add String interpolation into my class 🙂 

Happy coding! 😄

**Comment by comintern** [comment]
@sancarn That certainly looks intriguing, and I'm looking forward to examining it in more depth.

How are your c# chops (hint, hint)?...  😄

**Comment by sancarn** [comment]
@comintern Honestly, I've only ever worked with C# once to make a super basic app. Otherwise I'm a complete noob, mostly due to complete incompatibility with all IT systems I've worked with so far :P That being said, I am going to [try to host CLR from VBA](https://github.com/sancarn/VBA-STD-Library/blob/master/src/WIP/STD_Runtimes_CLR.cls) at some point to maybe get around that... 😛
