### ISSUE TITLE
Unify install folders

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#326]
The x86 and x64 installers are not installing Rubberduck in the same folder. That's awkward and needs to be fixed.

Other installer properties need to be unified as well.

**Comment by ckuhn203** [comment]
@retailcoder  Where is the x64  installer pointed?

**Comment by retailcoder** [comment]
`%APPDATA%\Rubberduck.Install`

**Comment by ckuhn203** [comment]
Let's go with `%APPDATALOCAL%\Rubberduck` as the default. I *think* the path you have there will try to install it in the `Roaming` directory. That's probably not a good thing. 

We need to figure out if changing the default location breaks the upgrade path for the installer though. It shouldn't, but I want to confirm it.

**Comment by retailcoder** [comment]
1.3 32-bit installer seemed to be configured to install under *program files\rubberduck\rubberduck* - changing it to *program files\rubberduck* in both installers.
