### ISSUE TITLE
@TestMethod marker has no effect on a method named "TestInitialize" or "TestCleanup"

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#329]
Test methods are discovered in two ways:
 
 - Either they begin with the word "Test"
 - Or they're decorated with a "@TestMethod" marker

Test setup & teardown methods are also discovered in two ways:

 - Either they are named "TestInitialize" / "TestCleanup"
 - Or they're decorated with a "@TestInitalize" / "@TestCleanup" marker

As a user I would expect a method named "TestInitialize" decorated with a "TestMethod" marker, to be treated as a test method, but version 1.21 ignores them.

**Comment by ckuhn203** [comment]
I'm all for completely ditching discovery via name. Just throwing that out there.

**Comment by retailcoder** [comment]
That might not be crazy at all. It's an API breaking change, but not crazy at all.

**Comment by retailcoder** [comment]
That's really just a funky edge case, flagging it as "by design" and moving on.
