### ISSUE TITLE
Extensions.VBComponentsExtensions.QualifiedName():   The handle is invalid.

### ISSUE THREAD

**Issue by mwolfe02** [retailcoder/Rubberduck#331]
I'm sorry I don't have anything more than the stack trace to offer here.  If there's something more I can provide, please let me know.

------

	See the end of this message for details on invoking 
	just-in-time (JIT) debugging instead of this dialog box.

	************** Exception Text **************
	System.Runtime.InteropServices.COMException (0x80070006): System Error &H80070006 (-2147024890).   The handle is invalid. 
	   at Microsoft.Vbe.Interop._VBComponent.get_Name()
	   at Rubberduck.Extensions.VBComponentsExtensions.QualifiedName(VBComponent component) in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\Extensions\VBComponentsExtensions.cs:line 16
	   at Rubberduck.VBA.RubberduckParser.Parse(VBComponent component) in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\VBA\RubberduckParser.cs:line 57
	   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.ParseModule(VBComponent component, QualifiedModuleName& qualifiedName) in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 280
	   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.<>c__DisplayClass2c.<CreateModuleNodesAsync>b__2b() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 264
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.<CreateModuleNodesAsync>d__2e.MoveNext() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 264
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Rubberduck.UI.CodeExplorer.CodeExplorerDockablePresenter.<>c__DisplayClassd.<<AddProjectNodes>b__c>d__f.MoveNext() in c:\Users\Christopher\Source\Repos\Rubberduck\RetailCoder.VBE\UI\CodeExplorer\CodeExplorerDockablePresenter.cs:line 183
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)

	************** Loaded Assemblies **************
	mscorlib
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18444 built by: FX451RTMGDR
		CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
	----------------------------------------
	Rubberduck
		Assembly Version: 1.21.5553.34023
		Win32 Version: 1.21.1.0
		CodeBase: file:///C:/Program%20Files%20(x86)/Rubberduck/Rubberduck/Rubberduck.dll
	----------------------------------------
	System.Windows.Forms
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
	----------------------------------------
	System.Drawing
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
	----------------------------------------
	System
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
	----------------------------------------
	System.Core
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
	----------------------------------------
	Antlr4.Runtime.net45
		Assembly Version: 4.3.0.0
		Win32 Version: 4.3.0.0
		CodeBase: file:///C:/Program%20Files%20(x86)/Rubberduck/Rubberduck/Antlr4.Runtime.net45.DLL
	----------------------------------------
	System.Xml
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
	----------------------------------------
	System.Configuration
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
	----------------------------------------
	Microsoft.GeneratedCode
		Assembly Version: 1.0.0.0
		Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
	----------------------------------------
	Accessibility
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
	----------------------------------------
	CustomMarshalers
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
	----------------------------------------
	Microsoft.CSharp
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
	----------------------------------------
	System.Dynamic
		Assembly Version: 4.0.0.0
		Win32 Version: 4.0.30319.18408
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
	----------------------------------------
	Anonymously Hosted DynamicMethods Assembly
		Assembly Version: 0.0.0.0
		Win32 Version: 4.0.30319.18444 built by: FX451RTMGDR
		CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
	----------------------------------------

	************** JIT Debugging **************
	To enable just-in-time (JIT) debugging, the .config file for this
	application or computer (machine.config) must have the
	jitDebugging value set in the system.windows.forms section.
	The application must also be compiled with debugging
	enabled.

	For example:

	<configuration>
		<system.windows.forms jitDebugging="true" />
	</configuration>

	When JIT debugging is enabled, any unhandled exception
	will be sent to the JIT debugger registered on the computer
	rather than be handled by this dialog box.

**Comment by ckuhn203** [comment]
@mwolfe02 what were you doing when this happened and what environment are you running Rubberduck in?

**Comment by mwolfe02** [comment]
I am running Access 2002/XP on Win 7 64-bit.  The error occurred immediately after performing a compact/repair.  I assume it was performing the initial parse of the code for the Code Explorer window.

Unfortunately, I just opened the same file and the Code Explorer finished populating without error.  So I'm not sure how reproducible this is.  Perhaps you could trap this specific exception and show a message box with some relevant local variable values to assist in future troubleshooting?  Maybe include this issue # in the MsgBox itself?

**Comment by retailcoder** [comment]
Acquiring a VBComponent's name threw that COMException. Interesting.

**Comment by ckuhn203** [comment]
Just repro'd in 2010.

1. Open Access
2. Open VBE
3. Quickly switch back to Access and Perform Compact & Repair.

A compact and repair closes the VBE, so this LoC

>        at Microsoft.Vbe.Interop._VBComponent.get_Name()

Obviously can't execute. I don't know for sure without looking at the code, but I think our ***only*** option is to catch `COMException`. Even then, there may not be much we can do because the entire VBE (and theoretically the Add-In) gets unloaded.

**Comment by retailcoder** [comment]
Swallowing the `COMException` at the `QualifiedName()` extension method level would be bad, because then we'd have a `QualifiedName` without a valid component name, ..which could have nasty side-effects in other circumstances.

I think our best option might be to catch the `COMException` at the `Parse(VBComponent)` level, and handle it by returning a `null` parse result (and then by *not* adding the `null` to the results collection).

In this specific situation, the outcome would be a fixed issue; in other situations, the most visible outcome would be a missing module in the code explorer (other consequences include missing inspection results for the unparsed module).
