### ISSUE TITLE
Add ability to exclude changes from a Commit

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#335]
The first version of our integrated source control will always commit all changes. Add the ability to exclude changes.

**Comment by ckuhn203** [comment]
GitProvider was updated to allow this change in commit afe8e94.

The UI still needs to be updated to allow the moving of items in between the various lists.

**Comment by ckuhn203** [comment]
We can now drag and drop items between Included and Excluded.

We still need to add the same functionality between Untracked and Included.
Items should only be able to move to Included from Untracked, not to Excluded.
Should not be able to drag any items *into* Untracked. That is a task better left to the command line. It's complicated and even the MS VS team hasn't quite gotten that right in their integration efforts.

**Comment by retailcoder** [comment]
Really? I'd be happy if Rubberduck's SC behaves half as decently as VS's! :smile:

**Comment by ckuhn203** [comment]
Lol... We'll see how it goes. I need to figure out how to differentiate between the different grid views. According to the docs there's a name property, but it's not showing in intellisense. 

https://msdn.microsoft.com/en-us/library/system.windows.forms.datagridview%28v=vs.110%29.aspx
