### ISSUE TITLE
GoTo Anything

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#340]
Let's create a little window that allows the user to type in any identifier name and navigate to it. There should be a dynamic dropdown for easier selection, and the displayed text should include the name of the module each identifier is declared in.

For example, typing "do" could bring up...

 - "DoSomething (in Module1)"
 - "DoesThisWork (in TestModule3)"
 - "Directions.Down (in Navigation)"

...items should be sorted alphabetically, and ideally have an icon representing their declaration type (method, enum, const, event, etc.) - this might not be easily done wih 100% WinForms code though.

**Comment by retailcoder** [comment]
Let's try some WPF interop here, and achieve that full-featured dropdown.

**Comment by retailcoder** [comment]
Commit 7e512a80922f94ff750ba7fd5aae23de1bdda646 closes this issue relatively well. Missing navigate-on-enter (i.e. perhaps "thisw[ENTER]" should navigate to `ThisWorkbook` and close the dialog), and there's something causing a delay when dropping the dropdown, and the caching required adding new `DeclarationType` entries (`UserForm`, for example), but there are implications in the identifier declaration and resolution code so I didn't bother with them. Perhaps create an overload of the indexer that takes a `DeclarationType` and an `Accessibility` parameters instead of just a `Declaration`, so that we could "override" the declaration's declaration type and fetch the "UserForm" icon for a form even though a form has a "Class" declaration type.

**Comment by Hosch250** [comment]
:+1:
