### ISSUE TITLE
Renaming an interface breaks implementations

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#353]
Consider an `IView` interface specifying a `Show` member:

    Public Sub Show()
    End Sub

An implementing class would have a method like this:

    Implements IView

    Public Sub IView_Show()
    End Sub

So, renaming `IView` to `ISomethingElse` would result in this implementation:

    Implements ISomethingElse

    Public Sub IView_Show()
    End Sub

...which breaks the code.

**Comment by PetLahev** [comment]
Hi Guys, I've been looking at this in code. I found it under UI - Refactorings - Rename. I'd like to help you with this, can I? If so, I'd write first unit tests for that (I've already started ..) which branch should I use (next)?

**Comment by ckuhn203** [comment]
Yes @PetLahev. `next` is our development branch. You can fork and submit pull requests to it. It's up to date to the best of my knowledge. If you have a need to mock anything for your tests, we're using Moq. Give us a shout here or [in chat](http://chat.stackexchange.com/rooms/14929/vba) if you need anything.

**Comment by retailcoder** [comment]
Awesome! Pull the *Refactorings* branch - I'm working on that one. You'll notice a crapload of false positives in code inspections, too.. I'm planning on focusing on that problem over the next few days, so your contributions to refactorings are more than welcome!


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: PetLahev <notifications@github.com> </div><div>Date:2015-04-02  09:46  (GMT-05:00) </div><div>To: retailcoder/Rubberduck <Rubberduck@noreply.github.com> </div><div>Cc: Mathieu Guindon <retailcoder@gmail.com> </div><div>Subject: Re: [Rubberduck] Renaming an interface breaks implementations (#353) </div><div>
</div>Hi Guys, I've been looking at this in code. I found it under UI - Refactorings - Rename. I'd like to help you with this, can I? If so, I'd write first unit tests for that (I've already started ..) which branch should I use (next)?

**Comment by ckuhn203** [comment]
P.S. Thanks for lending a hand!

**Comment by retailcoder** [comment]
Actually I'm working on the false positives issue / code inspections, in the `GrammarIsFun` branch, so if you work in `Refactorings` we shouldn't collide :)

**Comment by retailcoder** [comment]
Ok, I'm ready to tackle that one. ...tomorrow.

**Comment by PetLahev** [comment]
OK, I'm sorry I couldn't help. Still struggling with the unit tests

**Comment by retailcoder** [comment]
Hey no problem, the unit tests are just as important if not more!

Sent from my Samsung mobile
