### ISSUE TITLE
Too many subfolders in the x64 install path

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#360]
Install folder for 1.22 x64 is 

    C:\Program Files (x86)\Rubberduck\Rubberduck\

The extra "Rubberduck" subfolder should be removed for next release

**Comment by daFreeMan** [comment]
This also applies to the x86 32-bit version:

`C:\Program Files\Rubberduck\Rubberduck`

**Comment by ckuhn203** [comment]
Guys, this is a nice idea and all, but we already have a bunch of people out there with it installed in this location. Do we have any idea how changing this will affect an upgrade? I don't. It needs to be tested if we do this.

**Comment by retailcoder** [comment]
Let's just change it once and for all, and include a note to perform a manual uninstall of the previous version.
