### ISSUE TITLE
Fix on implicitly typed Consts wipes out other variables if line has multiple declarations.

### ISSUE THREAD

**Issue by comintern** [retailcoder/Rubberduck#368]
Code inspection correctly reports this line...

`Const Foo = 1, Bar = 2, Foobar = 3`

...with each of the variables as implicitly Variant, and as having multiple declarations on one line.  However if the item for any of the variables has the "Declare as explicit Variant" fix applied, it removes the other declarations.  For example, if the 'Bar' variable is fixed, this is the resulting line:

`Const Bar As Variant = 2`

The expected result should be:

`Const Foo = 1, Bar As Variant = 2, Foobar = 3`

**Comment by retailcoder** [comment]
hmm this probably also applies to variable declarations, right?

**Comment by comintern** [comment]
No, Dim lines work as expected.

**Comment by retailcoder** [comment]
Interesting... it's the same code performing the rereplacement: https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Inspections/VariableTypeNotDeclaredInspectionResult.cs#L42

**Comment by retailcoder** [comment]
Oh, I just saw where the bug is..

**Comment by retailcoder** [comment]
Fixed!
