### ISSUE TITLE
ProcedureNotUsed should ignore workbook/worksheet events

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#397]
Workbook event handler procedures are deemed "never used' by the `ProcedureNotUsedInspection`:

    Private Sub Workbook_Open()
        '...
    End Sub

These are HostApplication-specific, but they should be ignored nonetheless.

**Comment by Hosch250** [comment]
Works for all entered document names.

**Comment by Hosch250** [comment]
See an un-blocked case? Enter the name here: https://github.com/retailcoder/Rubberduck/blob/next/RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs#L91
