### ISSUE TITLE
Add an option to include VBA Standard Library project in the Code Explorer

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#426]
With every member of the VBA standard library known to Rubberduck, there's not much stopping us from enabling our users to browse the `VBA` project in the code explorer.

**Comment by ckuhn203** [comment]
Can you expand on what this is and what it's meant to accomplish? 

> As a VBA dev I would like Rubberduck to ? so I can ?

I'm not quite getting this one.

**Comment by retailcoder** [comment]
Sure!

As a VBA programmer, I want to be able to see the modules and types defined
in the standard library in the code explorer, so that I can easily browse
all those pesky enums instead of looking them up on MSDN.. and then I can
also easily find all references to any of them throughout my code.

Sent from my Samsung mobile

**Comment by ckuhn203** [comment]
Hmmm interesting for sure, but why not just open the object browser? Finding the references is a *neat* idea though.

**Comment by retailcoder** [comment]
Actually this might be more of a "bells and whistles" than anything else.
You can already find all references of any built-in declaration by
right-clicking them in the code pane.

Sent from my Samsung mobile

**Comment by ckuhn203** [comment]
It's a neat idea and I'm not going to stop you, but I would give this a [status-declined] if anyone else submitted this.

**Comment by retailcoder** [comment]
@ckuhn203 you're right. we have better things to do than implementing bells & whistles.
