### ISSUE TITLE
Reference path depends on username

### ISSUE THREAD

**Issue by JackDunnNZ** [retailcoder/Rubberduck#440]
Because the Rubberduck files are installed by default into the AppData folder (using 1.30), the current username is included in path to the reference when the VBA project. If the same project is opened on another a computer with a different username, the reference is marked as missing even if Rubberduck is present in the same folder on the new computer.

I develop an addin and test it across multiple Windows/Office combinations so it would be great if the references were able to transfer across seamlessly. Obviously I can fix it on my end by installing Rubberduck to a different folder, but just wondered if there might be a solution on your end?

BTW this tool is fantastic and has revolutionised my workflow! Hope to help out at some point if needed :+1:

**Comment by retailcoder** [comment]
Wow, thanks! I really needed this positive feedback today, after all the regression bugs I found in the 1.3 release!
I had a feeling there was a good reason to install under program files... you just gave me one on a silver platter! @ckuhn203 see? *that* is why we need it under program files! :wink:

Sent from my Samsung device

**Comment by ckuhn203** [comment]
It used to install to ProgramFiles by default *cough*. Does the new installer let you choose the installation directory? The old one did. I'm not sure since we moved to InnoScript. 

Cc: @Rossco

**Comment by retailcoder** [comment]
It does. I'll change it back to program files for 3.0.1 bugfix release.

Sent from my Samsung mobile

**Comment by ckuhn203** [comment]
Cool. I don't think we're going to able to get an admin-less install with the COM registration anyway.

**Comment by retailcoder** [comment]
1.3.0.1 fixed this - let us know how it goes! :)

**Comment by JackDunnNZ** [comment]
Works perfectly, thanks for the quick turnaround!
