### ISSUE TITLE
Installer should not ask to create a Start Menu folder

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#441]
Rubberduck is an add-in, and we're not packaging any kind of docs or other programs with it. The installer shouldn't try to create a start menu. Minimally, it should have `Don't create a Start Menu folder` checked by default.

![image](https://cloud.githubusercontent.com/assets/2716800/7474572/3e436354-f310-11e4-8bb8-ee645b81e2e7.png)

**Comment by retailcoder** [comment]
That thought occurred to me as well... but then seeing it was putting an
uninstall link and a link to rubberduck-vba.com, I thought it might not be
a bad idea at all.

Sent from my Samsung mobile

**Comment by ckuhn203** [comment]
Oh. well, then okay. I didn't allow it to do that, so I didn't know that.
