### ISSUE TITLE
"Find All References" does nothing for Procedures

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#442]
I don't know what more to say. Whether I select a procedure name, or if I try to do this from the Code Explorer, it doesn't do anything at all.

I can understand if this doesn't work for Procedures (it would be nice if it did!), but we shouldn't have it available in the Code Explorer context menu if it can't be used.

**Comment by retailcoder** [comment]
Is the procedure actually used anywhere in the same project?

...because if works for me:

![find all references works from the code explorer](http://i.stack.imgur.com/znxE8.png)

**Comment by retailcoder** [comment]
Perhaps there should be a message box saying "references to '[identifier]' not found" or something like that, when no references are found for an identifier.

**Comment by retailcoder** [comment]
Also that context menu needs to also work in the *project explorer* :)

**Comment by ckuhn203** [comment]
Yeah. I think that's what's going on. I put together a simple repo and it worked. It selected the single usage of it.

    Private Sub hello()
        goodbye
    End Sub
    
    Private Sub goodbye()
        Debug.Print "Bye!"
    End Sub


So, a message box alerting that nothing was found would be greatly beneficial (essential) here.

**Comment by retailcoder** [comment]
Yup. When there's only 1 reference to an identifier, the feature jumps to that reference - if there's more than 1, it shows the toolwindow. If there's none, it does nothing... for now.
