### ISSUE TITLE
ExportAsSourceFile extension method blows up if "Document" source file is empty

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#449]
The line that gets the text to export is assuming `CountOfLines` is greater than 0:

            if (component.Type == vbext_ComponentType.vbext_ct_Document)
            {
                var text = component.CodeModule.get_Lines(1, component.CodeModule.CountOfLines);
                File.WriteAllText(filePath, text);
            }

**Comment by retailcoder** [comment]
@ckuhn203 how to fix this depends on how we want to handle empty files. I *think* we should generate an empty one, so rolling back changes can be done.

**Comment by ckuhn203** [comment]
I think that an empty file would be the most accurate representation of the project. If we create an empty file, it can be modified outside of the editor and imported back in.

**Comment by retailcoder** [comment]
Shouldn't we track the document properties? Like if a sheet was "VeryHidden", do we want to have that information under source control?

**Comment by ckuhn203** [comment]
That's definitely a nice to have. Sounds like a `Rubberduck Source Control 2.0` feature.

**Comment by retailcoder** [comment]
Fine by me - we should consider an xml format then.

Sent from my Samsung mobile
