### ISSUE TITLE
Refactor/Extract Method should remove unnecessary variables from source

### ISSUE THREAD

**Issue by daFreeMan** [retailcoder/Rubberduck#461]
When running _Refactor/Extract Method_, declarations of variables that are only used in the new method should be removed instead of leaving them for a later clean up in _Code Inspections_.

When this code is refactored:

    Public Sub test1()
    Dim i As Integer
    Dim j As Integer

      i = 10
      For j = 1 To i
        MsgBox j
      Next
  
    End Sub

it becomes this:

    Public Sub test1()
    Dim i As Integer
    Dim j As Integer

      i = 10
        Method1 i
  
    End Sub

    Private Sub Method1(ByVal i As Integer)
        Dim j As Integer
      For j = 1 To i
        MsgBox j
      Next
    End Sub

Leaving `Dim i as Integer` as an unused variable in `test1()` that will later need to be removed. The refactor code should borrow from the _Code Inspections_ logic to determine that `i` is no longer necessary, and simply remove it from the source method.

**Comment by retailcoder** [comment]
Closing for now, d819d77 addresses this - I've tested it with a number of test cases, but I'm still not very confident about it (see https://github.com/retailcoder/Rubberduck/commit/d819d77c2e42a6f67e93cfcf5c0a3bb5c92771de#diff-4738c53e2e92f62297eb4dc2421780b5R113).

**Comment by retailcoder** [comment]
a1c4173 makes me more confident about it :smiley:
