### ISSUE TITLE
Something related to the TokenStreamRewriter has Serious Problems

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#462]
Say you have this code:

    Public Sub Foo(ByVal Var1 As Integer, _
                   ByVal Var2 As Integer)

        Debug.Print Var1
        Debug.Print Var2

    End Sub

If you rename Var1 to Var15, (example), then CTRL-Z twice to undo both renames, then rename Var2 to Var25, then the code becomes this:

    Public Sub Foo(ByVal Var15 As Integer, ByVal Var25 As Integer)

        Debug.Print Var1
        Debug.Print Var25

    End Sub

**Comment by retailcoder** [comment]
You need to Ctrl+Z more than twice to fully undo all changes to the code module. "Undo rename" isn't something that's currently a supported use case. This is native/normal behavior.

**Comment by retailcoder** [comment]
Just to clarify. You have this:

    Public Sub Foo(ByVal Var1 As Integer, _
                   ByVal Var2 As Integer)

        Debug.Print Var1
        Debug.Print Var2

    End Sub

Rename `Var1` to `Var15`, then you get this:

    Public Sub Foo(ByVal Var15 As Integer, ByVal Var2 As Integer)

        Debug.Print Var15
        Debug.Print Var2

    End Sub

So far so good. Then you Ctrl+Z / undo the rename and get this:

    Public Sub Foo(ByVal Var1 As Integer, ByVal Var2 As Integer)

        Debug.Print Var1
        Debug.Print Var2

    End Sub

And when you rename `Var2` to `Var25`, you get this?

    Public Sub Foo(ByVal Var15 As Integer, ByVal Var25 As Integer)

        Debug.Print Var1
        Debug.Print Var25

    End Sub

**Comment by retailcoder** [comment]
Behavior confirmed in 1.3.0.1 release. Houston, we have a bug!

**Comment by Hosch250** [comment]
This also affects the Remove refactoring.

**Comment by Hosch250** [comment]
This is caused by the TokenStreamRewriter.  When I was NOT using the TokenStreamRewriter in Remove Parameters (current version, as of now), I did not have this problem.  Now I switched to using the TokenStreamRewriter, and I have the problem.  What's more, as soon as I switched to using the TokenStreamRewriter, my code to update the calls stopped working perfectly, and it was working perfectly before.

**Comment by Hosch250** [comment]
By stopped working perfectly, it would sometimes seemingly, but consistently randomly not remove a parameter from a call.  Notably, the `Var4` in this call:

    Foo Var1, Var2, _
        Varx, Var4, _
        Var5

In this code:

    Public Sub Foo(ByVal Var1 As Integer, ByVal Var2 As String, ByVal Var3 As Byte, _
                   Optional ByVal Var4 As Object, Optional ByVal Var5 As Date, _
                   Optional ByVal Var6 As Long)
    End Sub

    Public Sub Goo(ByVal Var1 As Integer, _
                   ByVal Var2 As String, _
                   ByVal Varx As Byte, _
                   ByVal Var4 As Object, _
                   ByVal Var5 As Date, _
                   ByVal Var6 As Long, _
                   ByVal Var7 As Double)

        Foo Var1, _
            Var2, _
            Varx, _
            Var4
        Foo Var1, Var2, _
            Varx, Var4, _
            Var5
        
        Foo Var1, Var2, Varx, Var4, Var5, Var6
    End Sub

**Comment by Hosch250** [comment]
Additionally, neither of these calls are updated:

    Public Event Foo(ByVal arg2 As String)

    Private Sub Bar()
        Dim test1 As Integer
        test1 = 3

        Dim test2 As String
        test2 = "test"
    
        RaiseEvent Foo(4, "Hi!")
        RaiseEvent Foo(test1, test2)
    End Sub

**Comment by Hosch250** [comment]
This function call is updated when either parameter is removed:

    Private Function Foo(Value As Variant, other As Variant) As Integer
    End Function

    Private Sub Goo(test1 As Variant, test2 As Variant)

        Foo test1, test2

    End Sub

**Comment by Hosch250** [comment]
In this, both the getter and the setter are set to the same value:

    Private myFoo As Class4

    Public Property Get Foo(test As String, test1 As Integer) As Class4
        Set Foo = myFoo
    End Property

    Public Property Set Foo(test As String, newFoo As Class4)
        Set myFoo = newFoo
    End Property

**Comment by retailcoder** [comment]
When we parse the module, we return a TSR off the lexer stream; when the TSR is used in a refactoring, and then the refactoring is undone, when we redo the refactor/rename the parser sees nothing changed in that module and therefore doesn't re-parse it, so the refactoring is working off the cached parse results (which is fine), but then it still has the same modified TSR instance - that's what the problem is ;-)

**Comment by retailcoder** [comment]
Fixed for the rename refactoring - @Hosch250 you'll need to pull commit 8269554 into your dev branch and refactor a bit; since I removed `.Rewriter` getter and replaced it with a `.GetRewriter()` method that returns a TSR.

How I fixed it for in the rename refactoring was by [introducing a new local variable](https://github.com/retailcoder/Rubberduck/commit/826955414227b57b7086c90f8412de5264231ea6#diff-e1345ee6f626393d6f73137b00abab6eR252):

    var rewriter = targetModule.GetRewriter();

and then working off that `rewriter` instance.

**Comment by Hosch250** [comment]
:+1:
