### ISSUE TITLE
FileNumber grammar rule needs to work without a "#"

### ISSUE THREAD

**Issue by s3lli9** [retailcoder/Rubberduck#467]
Hi,
I use version 1.3.1 with Office 2013 (32-bit) on Windows 8.1 (64-bit).
In a module, if I use the following code:

`Open myFile For Input as 1`

the module disappears in the code explorer and is ignored by the inspector.

**Comment by ckuhn203** [comment]
@retailcoder looks like this one is back since the grammar change.

**Comment by retailcoder** [comment]
Thank you for your feedback! I suspect the 1 in "As 1" is tripping the *fileNumber* parser rule. Try this instead:

    Open myFile For Input As #1

I need to figure out a way to allow an integer literal there without a "#".

Note that a better practice would be to let VBA assign a free file number instead of hard-coding it, using the FreeFile function:

    Dim fn As Integer
    fn = FreeFile

    Open myFile For Input As #fn

**Comment by s3lli9** [comment]
Thank you for your reply.

Indeed, using the "#" the module does not disappear.

Thank you again for the quick response and congratulations for your work.

**Comment by ckuhn203** [comment]
Glad it worked out for you @s3lli9! I'm going to go ahead and re-open the issue until we can fix the bug though.

**Comment by retailcoder** [comment]
Good news here, redefining the `fileNuber` grammar rule as follows:

>     fileNumber : '#'? (ambiguousIdentifier | INTEGERLITERAL);

Seems to work fine, this code parses correctly:

    Sub DoSomething()
        Dim f As Integer
        f = FreeFile

        Open "test.txt" For Output As f
        Close f
    End Sub

As does this code:

    Sub DoSomething()
        Open "test.txt" For Output As 1
        Close 1
    End Sub
