### ISSUE TITLE
Configure project location

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#47]
In order to support source control integration, Rubberduck will need to export/import all code files to/from a given folder. Making this folder the workbook's location may not always be possible; first thing to do is to determine where the local repository is going to be located; we need a feature that will enable the user to specify that.

**Comment by ckuhn203** [comment]
This happens "under the covers" so to speak. The user can open or create a working directory from the GUI. Repository information is stored in the `SourceContropConfiguration` object which gets serialized to `%APPDATA%\Rubberduck\SourceControl.rubberduck`.
