### ISSUE TITLE
Export all code files to local repository

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#48]
Rubberduck needs a feature that will export all code files to a local repository.

**Comment by ckuhn203** [comment]
Add an extension method to VbProject for this. `ExportAll` or some such thing.
Good starting point here. https://github.com/ckuhn203/VBEX/blob/master/src/DevTools.bas

**Comment by ckuhn203** [comment]
This was recently merged into master. 

https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Extensions/VbProjectExtensions.cs#L36-L90
