### ISSUE TITLE
Import code files from local repository

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#49]
related: #48 - Rubberduck will need to be able to synchronize changes by finding all code files in the local repository, removing all project components with the same name, and importing the code files back into the VBA project.

**Comment by ckuhn203** [comment]
This was recently merged into master. 

https://github.com/retailcoder/Rubberduck/blob/master/RetailCoder.VBE/Extensions/VbProjectExtensions.cs#L36-L90
