### ISSUE TITLE
Reorder Parameters focus

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#498]
To reorder a methods parameters, you must click on the name of that method.  Should we allow the user to click the variables inside the method signature, or even in the method body, and open the menu for the parent method?

**Comment by retailcoder** [comment]
The most instinctive UX would be to right click any parameter in the signature. But we should allow it from any method call or anywhere in the signaturr. Inside method body could work, too.. but it's a stretch imo.

**Comment by Hosch250** [comment]
Sure.  Will do after I get the bugs ironed out and refactored good.

**Comment by Hosch250** [comment]
@retailcoder Oh, just to clear up any misunderstanding, you can click the method name from any call or the definition, and it will work.  You cannot click anywhere else, though.

**Comment by Hosch250** [comment]
Does not work for keywords.  Unsure how to fix.
