### ISSUE TITLE
Clean up resources

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#537]
The .resx under `Rubberduck.Properties` is a mess.

Let's move the common images to `RubberduckUI.resx`, clear or fix the broken ones (a bunch have this red (!) icon), and create a separate one for the ones used for `CommandbarButton` icons (bmp+mask).

**Comment by Hosch250** [comment]
I'll fix the ones with errors.

**Comment by retailcoder** [comment]
I don't see a real reason to have an `InspectionNames.resx` file. These resources should be moved to `RubberduckUI`.

**Comment by Hosch250** [comment]
Whoops, not close, just remove the InspectionNames.resx file.
