### ISSUE TITLE
QualifiedModuleName.cs throws Null Reference Exception

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#553]
I don't know why, but I can't test my changes to fix https://github.com/retailcoder/Rubberduck/issues/552

**Comment by Hosch250** [comment]
Isn't happening anymore.

**Comment by Hosch250** [comment]
Still happening for the Rename function, but the remove/reorder parameters refactorings work.

**Comment by retailcoder** [comment]
I'm not getting the exception. But I'm not getting a rename dialog either. Something's not right.

**Comment by retailcoder** [comment]
The `IsSelectedDeclaration` and `IsSelectedReference` implementations were relying on `QualifiedModuleName.Equals` which seems to be broken.
