### ISSUE TITLE
A Mockable Folder Browser dialog would be awesome

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#555]
There's some reasonably complicated logic in the SourceControlPresenter that can't be automatically tested because it uses a `FolderBrowswerDialog`. There has to be a better way. Find a mockable alternative.

        private void OnInitNewRepository(object sender, EventArgs e)
        {
            using (var folderPicker = new FolderBrowserDialog())
            {
                folderPicker.Description = "Create New Repository";
                folderPicker.RootFolder = Environment.SpecialFolder.MyDocuments;
                folderPicker.ShowNewFolderButton = true;

                if (folderPicker.ShowDialog() == DialogResult.OK)
                {
                    var project = this.VBE.ActiveVBProject;

                    _provider = new GitProvider(project);
                    var repo = _provider.InitVBAProject(folderPicker.SelectedPath);

                    _provider = new GitProvider(project, repo);

                    AddRepoToConfig((Repository)repo);

                    SetChildPresenterSourceControlProviders(_provider);
                }
            }
        }

        private void OnOpenWorkingDirectory(object sender, EventArgs e)
        {
            using (var folderPicker = new FolderBrowserDialog())
            {
                folderPicker.Description = "Open Working Directory";
                folderPicker.RootFolder = Environment.SpecialFolder.MyDocuments;
                folderPicker.ShowNewFolderButton = false;

                if (folderPicker.ShowDialog() == DialogResult.OK)
                {
                    var project = this.VBE.ActiveVBProject;
                    var repo = new Repository(project.Name, folderPicker.SelectedPath, string.Empty);
                    _provider = new GitProvider(project, repo);

                    AddRepoToConfig(repo);

                    SetChildPresenterSourceControlProviders(_provider);
                }
            }
        }

**Comment by retailcoder** [comment]
Inject something like this into the constructor:

    public interface IFolderBrowserFactory
    {
        IFolderBrowser Create();
    }

Then wrap the `FolderBrowserDialog` with an interface:

    public interface IFolderBrowser
    {
        DialogResult ShowDialog(string description, string rootFolder);
        SelectedPath { get; }
    }

The implementation will have an `IDisposable` field and should be `IDisposable` itself:

    public class FolderBrowser : IFolderBrowser
    {
        private readonly FolderBrowserDialog _dialog;

        public FolderBrowser(string description, string initialPath)
        {
            _dialog = new FolderBrowserDialog
            {
                Description = description,
                RootFolder = initialPath,
                ShowNewFolderButton = false
            };
        }

        public DialogResult Show()
        {
            return _dialog.ShowDialog();
        }

        public string SelectedPath { get { return _dialog.SelectedPath; } }

        public void Dispose()
        {
            _dialog.Dispose();
        }
    }

The client code can then just replace `new FolderBrowserDialog()` with `_factory.Create()`.

**Comment by ckuhn203** [comment]
I did this once and trashed it because I was unhappy with the results. (So it's *somewhere* in the commit log), but I like this approach much more than what I originally tried. I also like that this would allow us to swap out the built in dialog for something a little nicer down the road.

**Comment by retailcoder** [comment]
It's an *abstract factory*. That pattern is very useful with DI :wink:
