### ISSUE TITLE
Need more detailed parser events

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#559]
The parse progress window can remain a long while on "Parsing..." during the initial parse, or when there are lots of modules to parse; the identifier resolution seems much faster because it's raising an event for each module - let's make `RubberduckParser` raise an event every time it starts parsing a module, so as to update the parse progress window more often.

**Comment by ckuhn203** [comment]
Good call. :+1:

**Comment by Hosch250** [comment]
Potentially closed in last commit, needs verification.
