### ISSUE TITLE
GoTo Implementation needs to match the parent module, not just the member name...

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#561]
Find All Implementations finds implementations of other classes too:

![screenshot 4](https://cloud.githubusercontent.com/assets/6299719/7817175/ab075200-0398-11e5-999a-194f50196ccc.png)

**Comment by retailcoder** [comment]
:sweat_smile:

**Comment by retailcoder** [comment]
https://github.com/retailcoder/Rubberduck/commit/309887afbb18b69aa62a762b62b33b4344e4c1ed#commitcomment-11368452
