### ISSUE TITLE
Rename Interface Methods

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#562]
It doesn't update calls:
![screenshot 5](https://cloud.githubusercontent.com/assets/6299719/7818666/b11cf9d8-03a2-11e5-9174-351c5eee8472.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/6299719/7818667/b11f7b90-03a2-11e5-944b-03e80bbca0fa.png)

**Comment by retailcoder** [comment]
hmm looks like the rename refactoring is somehow assuming interface methods only ever get called from outside their module.

https://github.com/retailcoder/Rubberduck/blob/next/RetailCoder.VBE/UI/Refactorings/Rename/RenamePresenter.cs#L202
