### ISSUE TITLE
Fix localization issues

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#565]
Despite the resource strings having been translated, there are still a number of strings hard-wired into the UI's.

![localizing-is-hard](https://cloud.githubusercontent.com/assets/5751684/7852840/9e4825ea-04d2-11e5-99d4-39a698871aaa.png)

These strings should be read from the resources; there's likely other issues elsewhere, gotta hunt 'em down.

**Comment by Hosch250** [comment]
I believe I finished the Code Inspections Window.  All the other windows still have to be finished.  Remember to localize the tooltip text too.

**Comment by Hosch250** [comment]
Code Explorer window done.

**Comment by Hosch250** [comment]
Todo explorer done.

**Comment by Hosch250** [comment]
Test explorer done.

**Comment by Hosch250** [comment]
Just settings dialog and source control left, AFAIK.  Will finish later, have a headache.

**Comment by ckuhn203** [comment]
Please leave source control alone for now. I don't want to deal with a bunch of merge conflicts. We can localize it after I wrap up push/pull functionality. I should have that done this week.

**Comment by Hosch250** [comment]
@ckuhn203 Sure.

**Comment by Hosch250** [comment]
Settings dialog complete.

**Comment by Hosch250** [comment]
About window and source control still need to be localized.

**Comment by Hosch250** [comment]
About window done.

**Comment by Hosch250** [comment]
@ckuhn203 Did you ever finish Source Control?

**Comment by Hosch250** [comment]
Source control done.
