### ISSUE TITLE
Sort in Code Inspection Window

### ISSUE THREAD

**Issue by Hosch250** [retailcoder/Rubberduck#569]
Throws exception when sorting by severity icon.

**Comment by ckuhn203** [comment]
Is there a related commit???

**Comment by Hosch250** [comment]
@ckuhn203 Yeah, just forgot to reference it: https://github.com/retailcoder/Rubberduck/commit/d4b74a322a80ef216d4bd965155e81e82c97fafe

**Comment by ckuhn203** [comment]
:+1:
