### ISSUE TITLE
Add the Code Explorer context menu items to the native Project Explorer

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#576]
Code Explorer is great, but I want to be able to right-click a module in the native *project explorer* and have all the goodies, too.

**Comment by Hosch250** [comment]
They are in there, but they don't work.

**Comment by Hosch250** [comment]
RubberduckMenu.cs needs to be refactored to only be the menu, and not the logic for "Find All X..." and other things in the menu to continue here.
