### ISSUE TITLE
ModuleIntialize and ModuleCleanup are executing for each TestMethod

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#579]
As mentioned in #570, `@ModuleInitalize` and `@ModuleCleanUp` are running for each and every test method right now. They should only be executing once per test module.

## Repro:

    Option Compare Database
    Option Explicit
    
    Option Private Module
    
    '@TestModule
    Private Assert As New Rubberduck.AssertClass
    
    '@ModuleInitialize
    Public Sub ModuleInitialize()
        'this method runs once per module.
        Debug.Print "Module Initalize"
    End Sub
    
    '@ModuleCleanup
    Public Sub ModuleCleanup()
        'this method runs once per module.
        Debug.Print "Module Cleanup"
    End Sub
    
    '@TestInitialize
    Public Sub TestInitialize()
        'this method runs before every test in the module.
        Debug.Print "Test Intialize"
    End Sub
    
    '@TestCleanup
    Public Sub TestCleanup()
        'this method runs afer every test in the module.
        Debug.Print "Test Cleanup"
    End Sub
    
    '@TestMethod
    Public Sub TestMethod1() 'TODO: Rename test
        On Error GoTo TestFail
        
        'Arrange:
    
        'Act:
    
        'Assert:
        Assert.IsTrue True
        Debug.Print "TestMethod1 Successful"
    
    TestExit:
        Exit Sub
    TestFail:
        Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
    End Sub
    
    '@TestMethod
    Public Sub TestMethod2() 'TODO: Rename test
        On Error GoTo TestFail
        
        'Arrange:
    
        'Act:
    
        'Assert:
        Assert.IsTrue True
        Debug.Print "TestMethod2 Successful"
    
    TestExit:
        Exit Sub
    TestFail:
        Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
    End Sub

## Actual Output

> Module Initalize
Test Intialize
TestMethod1 Successful
Test Cleanup
Module Cleanup
Module Initalize
Test Intialize
TestMethod2 Successful
Test Cleanup
Module Cleanup

## Expected Output

> Module Initalize
Test Intialize
TestMethod1 Successful
Test Cleanup
Test Intialize
TestMethod2 Successful
Test Cleanup
Module Cleanup

**Comment by retailcoder** [comment]
@ckuhn203 given the below code, I believe this issue is the same as #581, related to test discovery more than anything else:

            foreach (var module in modules)
            {
                RunModuleInitialize(module.Key.QualifiedModuleName);

                foreach (var test in module)
                {
                    if (tests.Contains(test))
                    {
                        RunMethodInitialize(test.QualifiedMemberName.QualifiedModuleName);
                    
                        var result = test.Run();
                        AllTests[test] = result;

                        RunMethodCleanup(test.QualifiedMemberName.QualifiedModuleName);


                        OnTestCompleted(new TestCompletedEventArgs(test, result));
                    }
                    else
                    {
                        AllTests[test] = null;
                    }
                }

                RunModuleCleanup(module.Key.QualifiedModuleName);
            }

**Comment by retailcoder** [comment]
Well this is dumb. `modules` in the above snippet, was defined as follows:

    var modules = tests.GroupBy(t => t.QualifiedMemberName);

Obviously this line is *screaming* "**I'm a bug!!**" just by the names involved; this is obviously the fix:

    var modules = tests.GroupBy(t => t.QualifiedMemberName.QualifiedModuleName);

And the new output:

> ModuleInitialize
TestInitialize
TestModule1_TestMethod1
TestCleanup
TestInitialize
TestModule1_TestMethod2
TestCleanup
ModuleCleanup
ModuleInitialize2
TestInitialize2
TestModule2_TestMethod1
TestCleanup2
TestInitialize2
TestModule2_TestMethod2
TestCleanup2
ModuleCleanup2
