### ISSUE TITLE
TestMethods aren't discovered if their signature doesn't begin the line

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#580]
## Repro:

1. Insert a new TestModule and TestMethod.

  ![image](https://cloud.githubusercontent.com/assets/2716800/7942805/a06b7876-092e-11e5-9903-0eff4dce06cf.png)

2. Insert at least one space before `Public Sub TestMethod1`.

        '@TestMethod
            Public Sub TestMethod1() 'TODO: Rename test
            On Error GoTo TestFail
        
            'Arrange:
    
            'Act:
    
            'Assert:
            Assert.Inconclusive
    
        TestExit:
            Exit Sub
        TestFail:
            Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
        End Sub

3. Refresh Test Explorer

  ![image](https://cloud.githubusercontent.com/assets/2716800/7942843/e0e8d0d8-092e-11e5-9d7d-76d03df8130d.png)

**Comment by ckuhn203** [comment]
Ping back #570 where this was discovered.

**Comment by retailcoder** [comment]
Fixed. This was caused by `Member.TryParse` using `string.StartsWith` to locate the signature line and the attribute on the line above.

    var signature = body.FirstOrDefault(line => Keywords.Any(line.StartsWith));

Fix:

    var signature = body.FirstOrDefault(line => Keywords.Any(line.Trim().StartsWith));

And..

    var attributes = MemberAttribute.GetAttributes(body.Take(signatureLineIndex)
                                                       .Where(line => line.StartsWith("'@")));

Fix:

    var attributes = MemberAttribute.GetAttributes(body.Take(signatureLineIndex)
                                                       .Where(line => line.Trim().StartsWith("'@")));
