### ISSUE TITLE
TestExplorer shows Intialize/Cleanup methods when it shouldn't

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#581]
Everything works as expected with the default names in the template the test explorer inserts.
This only manifests if the name of an `@TestInitalize` or `@TestCleanup` method is changed to something non-default, but not just *anything* non-default. I was only able to reproduce this behavior by appending a number to the end, like `TestInitialize2`. 

This only affects `Test` methods. `Module` methods are unaffected.

    '@ModuleInitialize
    Public Sub ModuleInitialize2()
        'this method runs once per module.
    End Sub
    
    '@ModuleCleanup
    Public Sub ModuleCleanup2()
        'this method runs once per module.
    End Sub
    
    '@TestInitialize
    Public Sub TestInitialize2()
        'this method runs before every test in the module.
    End Sub
    
    '@TestCleanup
    Public Sub TestCleanup3()
        'this method runs afer every test in the module.
    End Sub

![image](https://cloud.githubusercontent.com/assets/2716800/7943146/bcae1140-0930-11e5-9a79-1e9c185bdd65.png)

In comparison, this (quite unexpectedly) works as intended.

    '@TestInitialize
    Public Sub SetupTest()
        'this method runs before every test in the module.
    End Sub

    '@TestCleanup
    Public Sub TeardownTest()
        'this method runs afer every test in the module.
    End Sub

**Comment by ckuhn203** [comment]
Ping back #570 where this was discovered.

**Comment by retailcoder** [comment]
I had no repro on this one, but `ProjectTestExtensions.IsTestMethod(Member)` is now implemented as follows:

        private static bool IsTestMethod(Member member)
        {
            var isIgnoredMethod = member.HasAttribute<TestInitializeAttribute>()
                               || member.HasAttribute<TestCleanupAttribute>()
                               || member.HasAttribute<ModuleInitializeAttribute>()
                               || member.HasAttribute<ModuleCleanupAttribute>()
                               || ReservedTestAttributeNames.Any(attribute => 
                                   member.QualifiedMemberName.MemberName.StartsWith(attribute));

            var result = !isIgnoredMethod &&
                (member.QualifiedMemberName.MemberName.StartsWith("Test") || member.HasAttribute<TestMethodAttribute>())
                 && member.Signature.Contains(member.QualifiedMemberName.MemberName + "()")
                 && member.MemberType == MemberType.Sub
                 && member.MemberVisibility == MemberVisibility.Public;

            return result;
        }

Which is much easier to read, and clearly reads as correct.
