### ISSUE TITLE
AssertClass not working??

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#583]
Unit testing "works", in the sense that modules and methods can be added, and executed.

The problem is that the `AssertClass` throws an exception whenever VBA code uses it - it *looks* like a registration issue, but everything I've tried so far didn't get it to work.

We may have to fold `Rubberduck.UnitTesting` back into the main dll.

**Comment by ckuhn203** [comment]
I just tested this in the SourceControl branch. I don't have this issue. I can F8 through a call to `Assert` without any issues. So, yes, it's a registration issue, but it's more than likely related to the 64 bit version. 

I am having other issues though. I'm consistently getting an `InvalidCastException` in `QualifiedMemberName` when trying to refresh the Test Explorer.

        public override bool Equals(object obj)
        {
            try
            {
                var other = (QualifiedMemberName)obj; // can't cast obj to QualifiedMemberName
                return _qualifiedModuleName.Equals(other.QualifiedModuleName) && _memberName == other.MemberName;
            }
            catch (InvalidCastException)
            {
                return false;
            }
        }

Unfortunately, this is the only call on the stack. The first one is coming from external code. The UI maybe?

I'm going to pull down the current version of vNext and see how it's behaving there.

**Comment by ckuhn203** [comment]
No repro in 32 bit environment on vNext branch.

![image](https://cloud.githubusercontent.com/assets/2716800/8004805/c8063d16-0b50-11e5-889b-c30b64a0d22c.png)

**Comment by Hosch250** [comment]
@retailcoder @Mat'sMug Did you fix this?

**Comment by retailcoder** [comment]
Yeah.
