### ISSUE TITLE
Code Inspection should set a bookmark on each found suggestion

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#93]
VBA Code to set a bookmark

    Sub setbookmark()
        Dim editMenu As CommandBarPopup
        Set editMenu = Application.vbe.CommandBars("Menu Bar").Controls(2)
        
        Dim bookmarkMenu As CommandBarPopup
        Set bookmarkMenu = editMenu.Controls(editMenu.Controls.Count)
        
        bookmarkMenu.Controls(1).Execute
    End Sub

**Comment by ckuhn203** [comment]
Even if this could be done (and I'm not sure it can be), what's the benefit? Why did we want to do this?

**Comment by retailcoder** [comment]
The [probably bad] idea was to have a visual queue directly in the code
pane, but I don't think it's really needed. Let's decline this one.

**Comment by ckuhn203** [comment]
Done. [Status-Declined]
