### ISSUE TITLE
Function should be a procedure

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#98]
A `Function` declared without a return value, that is never assigned a return value, should be converted to a `Sub`.

    Public Function DoSomething() As Whatever
        'code
    End Function

Becomes

    Public Sub DoSomething()
        'code
    End Sub

QuickFixes:

 - [x] Convert to procedure
 - [ ] Assign return value

**Comment by retailcoder** [comment]
Moved to 1.2 - with the extension methods added for #168 (Extract Method), this one should be implementable in 10-15 minutes.

**Comment by retailcoder** [comment]
Ok an hour. "Assign return value" quickfix won't be implemented.

**Comment by ckuhn203** [comment]
I don't know if we're documenting these anywhere, but if we are, we should call out that Access developers should take particular care with this one and should perhaps turn it off/lower it's warning level. 

Why? Because Access ***Macros*** (yes, actual macros) can't call procedures. They can only call functions. Determining whether or not they are called that way is out of scope though.

**Comment by retailcoder** [comment]
Interesting, I didn't know that. Perhaps we could have a `'@access-macro` annotation that turns off that inspection? Or better, find a way for the code inspections to have access to the host app type, so that in Access this inspection only applies to `Private` functions?

**Comment by ckuhn203** [comment]
As an access dev, I would actually prefer the annotation. It completely clarifies intent and yet still allows me to run the inspection on the rest of my code base.

> Why is this a function? 

An hour later...

> Oh. I call it from a macro. I better mark it with that fancy comment to tell a Rubberduck to stop telling me about it. 

Looks at the code six months later...

> Why is this a function? Oh. Look at that comment. It's called by a macro.

**Comment by retailcoder** [comment]
:+1:
